### ISSUE TITLE
Implement CoreWebView2CustomSchemeRegistration for custom IPC schema

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#100]
@heapwolf started work implementing `CoreWebView2CustomSchemeRegistration` for custom schemas in e77bbc50533e898e7b8c2d428cf692e0d5fd0722, but was removed in 35467ec09f41ee5df6685513efb5f35358fe6afc to get around compilation errors.

Investigate bringing back `CoreWebView2CustomSchemeRegistration` so Windows can use `ipc://` instead of `http://` to intercept requests.

Example implementation: https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/AppWindow.cpp#LL1208C28-L1208C71

**Comment by lamiazar** [comment]
@jwerle I don't know if this was implemented.

**Comment by jwerle** [comment]
this is done
