### ISSUE TITLE
Automatically log output to known location

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#112]
Log all output to a known log file. Necessary for two reasons:

1. Tests in Windows can't read normally from `stdout` so the log file must be checked for success.
2. Useful for future bug reports so we can request the log file from the user.

Main question is, where is the log file supposed to go for each platform? I'm most concerned about iOS and Android.

**Comment by chicoxyzzy** [comment]
For iOS it should be `tmp/`

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

**Comment by chicoxyzzy** [comment]
cc @mribbons

**Comment by mribbons** [comment]
This is fixed.
