### ISSUE TITLE
Bundle instead of building an application

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#123]
Instead of building a binary using an application's files, bundle them and pass that to `ssc` to be run. The a few advantages of doing it this way are:
1. Building apps takes far less time
2. Users are not required to install build tools (especially painful to do on Windows)
3. Native addon development becomes possible by allowing the user to build a shared library then having the app include that using a JS API.

**Comment by heapwolf** [comment]
no longer relevant
