### ISSUE TITLE
TypeScript definitions for global APIs

### ISSUE THREAD

**Issue by aleclarson** [socketsupply/socket#14]
When will TypeScript definitions be added for the global APIs?

**Comment by ccorcos** [comment]
Hmm. Seems like we might be able to find a build tool out there that generated typescript types from these JSDoc annotations...

https://github.com/socketsupply/io/blob/master/fs/index.js#L68-L75

```ts
/**
 * Asynchronously check access a file for a given mode calling `callback`
 * upon success or error.
 * @see {@link https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsopenpath-flags-mode-callback}
 * @param {string | Buffer | URL} path
 * @param {string=} [mode = F_OK(0)]
 * @param {function(err, fd)} callback
 */
```

I'm curious more generally why the Socket team has decided not to use Typescript though. It's such a lovely language. 😄

**Comment by nichoth** [comment]
There are some `.d.js` files that we have internally. I think the plan is to add types to the `io` module. The existing type file is becoming out of date though as the APIs are changing rapidly.

I have been using a [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) to good success.
