### ISSUE TITLE
Blank screen using react/svelte boilerplate

### ISSUE THREAD

**Issue by oskery** [socketsupply/socket#140]
Following the [docs](https://sockets.sh/) using a Mac M1 with svelte or react boilerplate I get an empty white screen when running `npm start`. Vanilla boilerplate works fine.

When inspecting the console (within the white screen) react boilerplate logs: 
`Not allowed to load local resource: "/path/appname/dist/mac/appname.app/Contents/Resources/index.js"`

With svelte I also get an error, but different: 
`TypeError: 'text/css' is not a valid JavaScript MIME type.`

### All I do is
1. xcode-select --install (or install Xcode app).
2. curl -s -o- https://sockets.sh/sh | bash -s
3. npx create-socket-app svelte/react
4. npm start

### I have tried
1. Reinstalling CommandLineTools and replacing it with Xcode app
2. On two different M1 machines with different OS versions etc. Same issue.

**Comment by jwerle** [comment]
@oskery this should be fixed! You should be able to skip step #2 and just do:

```sh
npm init socket-app react # or npx create-socket-app react
```

The other templates should work as well. If you are still running into the same issues, try `rm -rf ~/.npm/_npx` to clear the `npx` cache
