### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#144]
This commit broke the Windows CI https://github.com/socketsupply/socket/commit/00e2e6d9bcfff85aef1c7e2a8b8a96fd5d867482

https://github.com/socketsupply/socket/actions/runs/4063245908/jobs/6995257824

cc @jwerle @mribbons

**Comment by chicoxyzzy** [comment]
related issue https://github.com/socketsupply/socket/issues/139

**Comment by mribbons** [comment]
Resolved by https://github.com/socketsupply/socket/pull/146

**Comment by mribbons** [comment]
@chicoxyzzy #139 relates to android only, 
#138 definitely relates to this ticket.

**Comment by chicoxyzzy** [comment]
Fixed in #146. Thank you Mike!
