### ISSUE TITLE
OS dialog API

### ISSUE THREAD

**Issue by ccorcos** [socketsupply/socket#16]
Things like the native open file dialog would be great.

**Comment by heapwolf** [comment]
it works. Maybe not documented?

```js
    const filePaths = await system.dialog({
      type: 'open', // or 'save'
      defaultPath: lastNode?.pathname || '',
      allowFiles: true,
      title: 'Choose the function\'s main file'
    })

    if (!filePaths || filePaths.length === 0 || filePaths[0] === '') return

    const file = filePaths[0]
 ```

**Comment by ccorcos** [comment]
Oh sweet.

**Comment by heapwolf** [comment]
Oh, I think the reason why it's not documented is because I wanted to make the javascript part of the API conform to the api on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker)

**Comment by ccorcos** [comment]
Ah, thats cool. I'm trying to hunt around for where this code is, but I'm not seeing a dialog property on the system object: https://github.com/socketsupply/ssc-node/blob/master/index.js

**Comment by jwerle** [comment]
you can find it here: https://github.com/socketsupply/socket/blob/master/src/lib/desktop.js#L51
and its native implementation here: https://github.com/socketsupply/socket/blob/master/src/desktop/main.cc#L603

**Comment by trevnorris** [comment]
@jwerle Has this API been documented?

**Comment by chicoxyzzy** [comment]
The API has changed and is documented now
