### ISSUE TITLE
How to communicate between windows?

### ISSUE THREAD

**Issue by ccorcos** [socketsupply/socket#17]
I have a couple questions here.

1. Suppose I have a SQLite database and a multi-window application. SQLite needs to be running in a single process and shared amongst the windows. I see `system.send` and `system.receive` but I'm not sure how to specify a single process just for SQLite.
2. Is it possible to manage windows more granularly? Suppose I want to open a separate "help" window. Ideally, I could launch a window with some args to the renderer or something.

**Comment by nichoth** [comment]
the main process would open a single SQLite process, and the main process would manage the various windows.

Then in [system.receive](https://github.com/socketsupply/socket-sdk-examples/blob/desktop-preact-node/desktop-node-preact/src/main/index.js#L52), you would want to declare in the args you pass to `.send` which window you are talking to, if necessary.

Like for example:
```js
  system.send({ window: 0, event: 'backend.ready', value: true })
```

**Comment by ccorcos** [comment]
Hmm. That makes sense, but looking through this example, I'm a little confused where the window is getting created in the first place... https://github.com/socketsupply/socket-sdk-examples/blob/6112ea7ca960d3b235a4db7f5196c4678c4306e6/desktop-node-react/src/main/main.js

**Comment by chicoxyzzy** [comment]
With the recent changes we always create the window with index 0 before bootstrapping the backend process. It is still possible to manage windows from the backend process if necessary.

**Comment by chicoxyzzy** [comment]
in the [new API](https://github.com/socketsupply/socket/pull/171) it will work like this:
```js
import application from `socket:application`

const currentWindow = application.getCurrentWindow()
currentWindow.send({ window, event, value })
```

**Comment by chicoxyzzy** [comment]
I'm going to close this issue. We will have a beta release and updated docs in a few days. Please feel free to reopen again if there will be any issues after beta release
