### ISSUE TITLE
Idea to get mobile CI working

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#186]
Problem: std pipes and exit codes aren't easy to obtain from apps.

We could do mobile CI like this:
1. `socket.ini` defines a node script, let's call it `std-proxy`
2. `test-ios.js` passes `ssc` a `port`
3. `ssc` builds app with `-DSTDCOMMS_PORT=[port]`
4. in `runApp`, `ssc` runs `std-proxy [port]` and calls `->open()` but doesn't wait
5. `ssc` runs app as normal using headless call, but this would be a new `Process()` instance, we leave the old one in place for transparent replacement purposes
6. `App` runs tests. because `STDCOMMS_PORT` is defined, instead of sending `console.log()` to `stdWrite()`, it opens a connection to `std-proxy`'s serrver on  `[port]` and sends them there (We need something similar for `exitCode`)
7. `ssc` now calls `process->wait()`
8. Output from `std-proxy` is captured by  `ssc`, will be written to std pipes.
9. when `App` finishes tests, it sends `exitCode` to `std-proxy`
10. `ssc` receives `exitCode` from `std-proxy`, 
11. CI pass/failure status is posted as normal

`std-proxy` could also write logs.

This could also solve terminal / bluetooth permission issue.

**Comment by mribbons** [comment]
@chicoxyzzy Let me know your thoughts.

**Comment by chicoxyzzy** [comment]
That makes Node a pre-requisite. For iOS we can just open a process `log stream --subsystem="socket-webview" --predicate='process contains "{settings["meta_bundle_identifier"]}"'` and use `os_log` instead of `NSLog` to use the `socket-webview` log subsystem.

**Comment by chicoxyzzy** [comment]
I was able to see logs running this in my second terminal window
```sh
log stream --style syslog --predicate='process contains "javascript" AND message contains "TEST"'
Filtering the log data using "process CONTAINS "javascript" AND composedMessage CONTAINS "TEST""
Timestamp                       (process)[PID]
2023-02-20 01:50:11.801092+0400  localhost socket-runtime-javascript-tests-dev[24624]: TEST cwd: /Users/chicoxyzzy/Library/Developer/CoreSimulator/Devices/8378D170-9EC1-467B-A90D-3F842FE52FD1/data/Containers/Data/Application/4072DFD5-73BC-4893-A97C-769CA74C3358
```

**Comment by mribbons** [comment]
> That makes Node a pre-requisite for end developers.

This is targeting npm test, which is an issue for ssc devs?

Node is already pretty much a pre req as it is referenced as a build command in `test/settings.ini`

> For iOS we can just open a process `log stream --subsystem="socket-webview" --predicate='process contains "{settings["meta_bundle_identifier"]}"'` and use `os_log` instead of `NSLog` to use the custom `socket-webview` log subsystem.

Awesome, simple is best. 

Will this work on real hardware, or just simulator?

**Comment by mribbons** [comment]
> For iOS we can just open a process `log stream --subsystem="socket-webview" --predicate='process contains "{settings["meta_bundle_identifier"]}"'` and use `os_log` instead of `NSLog` to use the custom `socket-webview` log subsystem.

While this approach simpler, I feel that it is very platform specific (Won't resolve android). I noticed we are using @jwerle's logcat tool for android?

**Comment by chicoxyzzy** [comment]
> Node is already pretty much a pre req as it is referenced as a build command in test/settings.ini

It's not mandatory to use Node.js for build, this is just a bash command

> Will this work on real hardware, or just simulator?

This should work for both
