### ISSUE TITLE
Determine Win32 heap corruption

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#188]
Occasionally locally and in CI (https://github.com/socketsupply/socket/actions/runs/4226906753/jobs/7340838075#step:9:332) the test runner aborts with `STATUS_HEAP_CORRUPTION`.

This bug is a race condition. Need to run more testing to figure out what is triggering the bug.

**Comment by heapwolf** [comment]
Unable to reproduce. Also, logs are no longer available. Happy to reopen if this can be reproduced.
