### ISSUE TITLE
Move some of Socket APIs out of `window.parent`

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#19]
Thinking more about keeping all Socket APIs in `window.parent`, I think that this approach has a few cons:
- it's not safe to add our own methods and properties to `windows.parent`, because DOM spec could potentially add methods or properties with the same name
- keeping these properties in `windows.parent` could lead to a misconception that they are part of existing specs

I propose to polyfill only methods and properties that exist in the DOM spec and doesn't work in a web view. All other methods and properties should be moved to another safe namespace.

**Comment by heapwolf** [comment]
this conversation took a few turns and the history is hard to reference because it was in discord. but the result is good I think we can close this.
