### ISSUE TITLE
Publishing ssc for npm on windows

### ISSUE THREAD

**Issue by heapwolf** [socketsupply/socket#198]
The `OTP` code expires before the build is done, so you need to `cd` into the build directory after the build fails and publish from there (ie, `~/projects/socketsupply/socket/build/npm/Win32/packages/@socketsupply/socket-Win32-x64)` and then do a publish for both repositories...

```bash
npm publish --registry=https://npm.pkg.github.com --otp=XXXXXX --access=public
npm publish --otp=XXXXXX --access=public
```

**Comment by heapwolf** [comment]
For me it just fails saying that it’s required

**Comment by jwerle** [comment]
funny, NPM gives me a URL to go to where I enter my OTP code now 😅

**Comment by chicoxyzzy** [comment]
an we close this one?
