### ISSUE TITLE
title field in the ssc.config doesn't set window title on app start

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#20]

**Comment by heapwolf** [comment]
I think a while back I decided it should be api only. can we remove it from the config?

**Comment by chicoxyzzy** [comment]
I think that either all of `height`, `weight` and `title` should work from config or all of them should be API only. It feels more practical to me to be able to set title via config

**Comment by jwerle** [comment]
@heapwolf I think we should allow the window title to be set from config. WDYT ?

**Comment by chicoxyzzy** [comment]
title is `window.document.title` (and according `<title>` element now)
