### ISSUE TITLE
socket-win32-x64 / next release

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#205]
- [x] Resolve `import socket:*` issues
- [x] Check Clang version
- [x] Check Windows SDK
- [x] Only pop extra window if prompts are required, or get prompts working in NPM install process
- [x] Don't echo CXX env var in `ssc.cmd`
- [x] Replace CXX env var if it already exists
- [ ] Document process including ps1 scripts and install-pre-reqs.js

**Comment by chicoxyzzy** [comment]
can we close this issue?

**Comment by mribbons** [comment]
@chicoxyzzy let's keep it open until I document the entire FTE process.
