### ISSUE TITLE
Opening Web Inspector in debug mode prints warnings

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#22]
I found this solution. It's in Rust, but it has comments. We can try it https://github.com/tauri-apps/wry/commit/2eba8c9c26ff5f9512b0039ac04bc7fd27a5256f

**Comment by trevnorris** [comment]
@chicoxyzzy just want to confirm, is this a macOS only thing?

**Comment by chicoxyzzy** [comment]
yes, it's macOS-only

**Comment by chicoxyzzy** [comment]
fixed
