### ISSUE TITLE
Remove tags from complementary projects

### ISSUE THREAD

**Issue by TejasQ** [socketsupply/socket#220]
![A screenshot of this repo](https://user-images.githubusercontent.com/9947422/223117116-45988c54-ede6-4cee-bdcf-d36301df0d3e.jpg)

I noticed this repo has tags `tauri` and `electron` et al, but really doesn't use any of them and thus does nothing for the repo except steals some of their audience from the OSS community. I've heard from the community that this isn't a very good look for complementary open source projects, so I'd suggest removing these tags.

My intent here is for a more positive image of Socket and a friendlier OSS ecosystem. This is *just a suggestion*, of course, so feel free to close the issue and dismiss it.

**Comment by heapwolf** [comment]
Agreed! And removed :)
