### ISSUE TITLE
npm i doesn't produce working install on windows

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#240]
```powershell
PS C:\Users\test> npm i @socketsupply/socket -g

added 2 packages, and audited 3 packages in 10s
# ...
PS C:\Users\test> mkdir app
PS C:\Users\test> cd app
PS C:\Users\test\app> ssc init .
PS C:\Users\test\app> ssc build -r -o
PS C:\Users\test\app> $LASTEXITCODE
-1073741515
# At this point I installed vc_redist.x64.exe (vcruntime140_1.dll)
PS C:\Users\test\app> ssc build -r -o
• socket.ini not found in C:\Users\test\app 3ms
PS C:\Users\test\app> ssc init .
PS C:\Users\test\app> ssc build -r -o
• warning! $CXX env var not set, assuming defaults 0ms
• preparing build for win 1ms
• using 'C:/Users/test/AppData/Roaming/npm/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-win32-x64\' as 'SOCKET_HOME' 0ms
• package prepared 29ms
• Unable to build 337ms
• 'clang++' is not recognized as an internal or external command,
operable program or batch file.
 0ms
PS C:\Users\test\app>
```
`bin\install.ps1` needs to be included and ran on install as per https://github.com/socketsupply/create-socket-app

**Comment by lamiazar** [comment]
I just tested this and it's still an issue @mribbons 
```
C:\Users\16147\apptest>ssc init
.\bin\install.ps1 : File C:\Users\16147\AppData\Roaming\npm\node_modules\@socketsupply\socket\node_modules\@socketsuppl
y\socket-win32-x64\bin\install.ps1 cannot be loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\bin\install.ps1 -fte:all
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
    ```

**Comment by jwerle** [comment]
> I just tested this and it's still an issue @mribbons
> 
> ```
> C:\Users\16147\apptest>ssc init
> .\bin\install.ps1 : File C:\Users\16147\AppData\Roaming\npm\node_modules\@socketsupply\socket\node_modules\@socketsuppl
> y\socket-win32-x64\bin\install.ps1 cannot be loaded because running scripts is disabled on this system. For more
> information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:1
> + .\bin\install.ps1 -fte:all
> + ~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
>     ```
> ```

did you run this?

```ps1
Start-Process powershell -verb runas -wait -ArgumentList "Set-ExecutionPolicy Bypass -Force"
```

I see it mentioned on https://socketsupply.co/guides/#install

**Comment by lamiazar** [comment]
I first tried with PowerShell and I did  run ` Start-Process powershell -verb runas -wait -ArgumentList "Set-ExecutionPolicy Bypass -Force"` and I got an error, then I tried with `cmd`

**Comment by mribbons** [comment]
@lamiazar this is a separate issue, we can work that one out via discord.
