### ISSUE TITLE
I'm getting an error when I try to build an app on ubuntu with `npm`

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/socket#246]
I'm testing `FTE` on ubuntu, and I'm getting this error when I run `ssc build -r -o` :
```
• warning! $CXX env var not set, assuming defaults +1ms
• preparing build for linux +0ms
• using '/usr/local/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/' as 'SOCKET_HOME' +0ms
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy: No such file or directory [/home/mia/src/icon.png] [/home/mia/dist/linux/beepboop-dev_v1.0.0-1_amd64/usr/share/icons/hicolor/256x256/apps/beepboop-dev.png]
  ```
  ps: I used `npm i @socketsupply/socket -g` for the installation.

**Comment by chicoxyzzy** [comment]
this issue will disappear once we publish new packages to npm

**Comment by lamiazar** [comment]
updates on this issue:
I'm still not able to build `ssc` on ubuntu, I'm getting this errors now:
```
mia@mia:~$ npm i @socketsupply/socket -g 

added 2 packages in 4s
mia@mia:~$ ssc --version
Command 'ssc' not found, but there are 30 similar ones.
```
I already set up my npm prefix

**Comment by mribbons** [comment]
Hey @lamiazar,
How did you install nodejs?

Please post the output from the following:
```bash
which npm
echo $PATH
find . -name 'ssc.js'
```

**Comment by lamiazar** [comment]
> How did you install nodejs?

`sudo apt install node` , I have v18

**Comment by lamiazar** [comment]
So after I install the deps :
```
sudo apt install \
  build-essential \
  clang-14 \
  libc++abi-14-dev \
  libwebkit2gtk-4.1-dev \
  autoconf \
  pkg-config \
  libtool \
  curl
  ```
  I set up `rpm prefix` and then I run `npm i @socketsupply/socket -g`
  
  This is the error I get:
  ```
  mia@mia:~$ ssc --version
Command 'ssc' not found, but there are 30 similar ones.
```

**Comment by lamiazar** [comment]
This is now fixed by `editing and exporting` the `path` variable and setting `npm` prefix
https://github.com/socketsupply/socketsupply.co/pull/220
