### ISSUE TITLE
feat: child_process

### ISSUE THREAD

**Issue by Bellisario** [socketsupply/socket#254]
I'm building an app that requires a process spawn but I don't find any documentation of this feature.

Is there any way to spawn a child process from a Socket app (desktop environment)?

**Comment by SheilaSardellaYJ** [comment]
Yes, it is possible to spawn a child process from a Socket app in a desktop environment. Here are some steps you can follow:

First, you need to import the "child_process" module into your Socket app:

const { spawn } = require('child_process');


Next, you can use the "spawn" method to spawn a child process. The first argument to "spawn" should be the name of the command you want to run, and the second argument should be an array of arguments to pass to the command:

const child = spawn('ls', ['-l']);


This example would spawn a child process to run the "ls" command with the "-l" argument.

You can then use the "stdout" and "stderr" properties of the child process to capture the output of the command:

child.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

child.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

**Comment by Bellisario** [comment]
@SheilaSardellaYJ, thanks for your answer.

Yes, I tried but this seems not to work.

I had to add `child_process` to external rollup option (on build) and the application compiles but then there is this console error: `TypeError: Module specifier, 'child_process' does not start with "/", "./", or "../".` and the application doesn't work.

**Comment by chicoxyzzy** [comment]
It is possible to spawn a process in Socket application with help of backend (such as Node, Deno or Bun). We have a simple example on how to use [Node backend](https://github.com/socketsupply/socket-examples) (this one uses global `node` command) and open PR on how to use Node backend which is embedded in the application (we have open PR in the examples repo)

**Comment by Bellisario** [comment]
@chicoxyzzy, thanks it works!

Closing this issue.

**Comment by chicoxyzzy** [comment]
We may consider to implement this

**Comment by heapwolf** [comment]
implemented in `platform-service-worker` branch to be merged into master and released this week.
