### ISSUE TITLE
Can't import from @socketsupply

### ISSUE THREAD

**Issue by fivestones** [socketsupply/socket#258]
I'm trying to follow along with the demo on youtube (https://www.youtube.com/watch?v=PhTjKtrpCYk) and when I try to run it (after adding `import { Peer, hash } from '@socketsupply/socket-api/p2p.js'`) it fails because it can't find p2p.js. How do I go about setting it up so it will find this and work? I have installed the node modules, and I see `p2p.js` in my `/usr/local/lib/node_modules/@socketsupply/socket/p2p.js`. I'm just not sure what I'm doing wrong.

I have installed @socketsupply/socket (following the youtube demo video, `npm install @socketsupply/socket -g`.

Initially my error was just
```
Could not resolve "@socketsupply/socket-api/p2p.js"

    src/index.js:1:27:
      1 │ import { Peer, hash } from '@socketsupply/socket-api/p2p.js'
```
I was able to get rid of that error by doing `npm link @socketsupply/socket` from my project root folder to link the globally installed npm module to the local project, and then by changing the code to be `import { Peer, hash } from '@socketsupply/socket/p2p.js'` (changed socket-api to just socket). But while that imports p2p.js successfully, it still errors with
```
Import "Peer" will always be undefined because the file "../../../../usr/local/lib/node_modules/@socketsupply/socket/p2p.js" has no exports [import-is-undefined]
```
and I had the same warning with the hash function. The app ran, but the functions (e.g., changing the background color when clicking on it) didn't work.

### What OS are you using (`uname -a`, or Windows version)?

MacOS 13.2.1 on M1 apple silicon

### What programming language are you using (C/C++/Go/Rust)?

javascript, node.js

### What did you expect to see and what you saw instead?

I thought the demo app would run, but it just says it can't find p2p.js.

**Comment by chicoxyzzy** [comment]
`socket-api` package is deprecated. It's an internal `socket:p2p` module now

**Comment by fivestones** [comment]
So how do I use this? Just `import { Peer, hash } from socket:p2p`?

**Comment by fivestones** [comment]
I tried that, and no error, or warnings! Great! But the app still doesn't really work (I see the window with the Hello World and socket runtime text, but clicking on the background doesn't do anything the change the color. I guess I need to start debugging?

Where would I find the documentation to tell me about socket:p2p?

And is there a better tutorial/demo I should follow along with now since it seems like things in that video aren't up to date any more?

**Comment by jwerle** [comment]
Hi @fivestones we have yet to release `socket:p2p` into the runtime standard library. We'll have a release soon along with updated documentation and up-to-date ancillary support media that should help you.

**Comment by fivestones** [comment]
> Hi @fivestones we have yet to release `socket:p2p` into the runtime standard library. We'll have a release soon along with updated documentation and up-to-date ancillary support media that should help you.

That sounds great. Thanks!

**Comment by chicoxyzzy** [comment]
Can we close this one? I think it's `socket:peer` module?

**Comment by jwerle** [comment]
> Can we close this one? I think it's `socket:peer` module?

yep!
