### ISSUE TITLE
Install on win11 (via powershell), `ssc` not persisted in path

### ISSUE THREAD

**Issue by getify** [socketsupply/socket#263]
In powershell, I just did a first-time install/build of `ssc` on win11, via the `install.ps1` script. It eventually successfully build `ssc` and put it (temporarily, it seems) into my path, so that from the command line I could issue `ssc --version` and it worked fine. I was even able to run `ssc init` and `ssc build -r` to get the "Hello World" app running.

However, when I restarted powershell, `ssc` was no longer in my path. I have to manually access its location, like:

```cmd
C:\Users\my-user\AppData\Local\Programs\socket\bin\ssc.exe --version
```

Seems like the path change that's temporary after the `install.ps1` script finishes, should just permanently alter my path. Perhaps it could ask if I want my path altered, but it should do so for me if I want it to.

**Comment by mribbons** [comment]
Resolved.
