### ISSUE TITLE
ssc.config not found

### ISSUE THREAD

**Issue by ccorcos** [socketsupply/socket#288]
Hey there, I'm just going through your documentation and leave some feedback about my experience.

1. When it says to run ` npx create-socket-app react`, it could say "create a new directory for your project and then run ` npx create-socket-app react`".

More importantly...

2. When I try to run the app: `ssc build -r --port=8000`, I get the error: `• ssc.config not found in /Users/chet/Code/js/journal/. +0ms`

I haven't done much debugging here yet, but I figured you'd want to update your docs.

**Comment by ccorcos** [comment]
Ah, but `npm start` works. Not sure why...

You docs also say `--target=iossimulator` but it should be `--platform`

**Comment by ccorcos** [comment]
With the default project, I'm running `"start": "ssc build -r -o --platform=ios-simulator",` and the page is blank:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1794527/228421344-71264d0c-0b6a-4093-bc46-d75705df1087.png">


No Simulator submenu under Safari > Develop
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1794527/228421459-b87a9b66-e6f6-4a7e-9471-c8a0a264f2a7.png">

**Comment by chicoxyzzy** [comment]
> You docs also say --target=iossimulator but it should be --platform

This is fixed in the new docs, we didn't publish them yet

Published `npm` is also outdated. We will update everything soon. Sorry for inconvenience

**Comment by chicoxyzzy** [comment]
cc @heapwolf about the `--target` -> `--platform` docs fix

**Comment by chicoxyzzy** [comment]
`npx create-socket-app` now ensures that current directory is empty before creating files
