### ISSUE TITLE
Crash when running the `ssc` from a 3rd party terminal application

### ISSUE THREAD

**Issue by juliangruber** [socketsupply/socket#3]
### What OS are you using (`uname -a`, or Windows version)?

```bash
$ uname -a
Darwin Julians-MacBook-Pro.fritz.box 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

macOS 12.6

### What programming language are you using (C/C++/Go/Rust)?

```bash
$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ go version
go version go1.18.4 darwin/amd64
$ rustc --version
zsh: command not found: rustc
```

### What did you expect to see and what you saw instead?

```bash
$ cd desktop-node-react
$ ssc compile -r .
• warning! $CXX env var not set, assuming defaults +0ms
• preparing build for mac +9ms
• package prepared +198ms
• ran user build command +138ms
• compiled native binary +30027ms
• Creating Window#0 +2ms
• Creating Window#1 +166ms
• Showing Window#0 (seq=0) +44ms
```

![Screenshot 2022-10-04 at 18 56 14](https://user-images.githubusercontent.com/10247/193880439-864c962a-571c-404f-9448-c2b54b37c6e0.png)

Full output: https://gist.github.com/juliangruber/96d4d8dab602a2393e53de45c98b295e

**Comment by heapwolf** [comment]
Permissions on latest MacOS prevent programs from running that are not signed, this can be easily overridden from the settings panel. But we should catch this crash and output a more friendly message.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/136109/193881540-ab5bf1f8-4d08-4435-8f4a-a9aee09e40ab.png">

**Comment by juliangruber** [comment]
It worked after enabling Terminal in this screen, and switching from iTerm2 to Terminal 🙏

**Comment by chicoxyzzy** [comment]
iTerm2 should work if you add it on Bluetooth tab
https://sockets.sh/troubleshooting/#application-crashes-on-start

**Comment by juliangruber** [comment]
iTerm2 worked for me too, after adding it to the Developer Tools tab, in this example

**Comment by trevnorris** [comment]
Accidentally remove the documentation tag for a moment.

@heapwolf Is this something we need to document?

**Comment by heapwolf** [comment]
We documented it but we need to do a fix for this still, it's been kind of low on the list but let's prioritize it for the stable release this month.

**Comment by heapwolf** [comment]
fixed.
