### ISSUE TITLE
Android / Linux / arch64 / arm64 build host support

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#306]
Currently static libraries and apps can't be built on Linux aarch64 due to ndk incompatibility:

```
/home/user/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-linux-android -v
/home/user/src/socket/bin/functions.sh: line 26: \
/home/user/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: \
cannot execute binary file: Exec format error
```

NDK does not ship with linux / aarch64 compatible binaries:
https://github.com/android/ndk/discussions/1692 
https://issuetracker.google.com/issues/227219818#comment15

MacOS aarch64 is supported by NDK 25.0.8775105.

**Comment by lamiazar** [comment]
@jwerle should we add a note about this ^ somewhere on the docs?

**Comment by jwerle** [comment]
> @jwerle should we add a note about this ^ somewhere on the docs?

yes, we absolutely should!

**Comment by lamiazar** [comment]
This is now added as a note on the docs
