### ISSUE TITLE
Powershell ExecutionPolicy

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#315]
Signing ps1 scripts isn't a complete solution because npm generated scripts will never be signed (ssc.ps1).

1. Check policy using Get-ExecutionPolicy
2. Use powershell -runas to run `Set-ExecutionPolicy bypass /a` - Note that this could be considered too permissive, must inform user on setup
3. Investigate npm docs on ps1 bin scripts re bin scripts being converted to ps1

**Comment by lamiazar** [comment]
@mribbons Can we close this one ?
Since the instruction were added to the docs.
