### ISSUE TITLE
Linux / npm i, npx paths should have a first time experience setup installer

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#320]
This would identify issues like missing or out of date clang, webgtk etc.

cc @lamiazar

**Comment by jwerle** [comment]
@mribbons I think this was solved in https://github.com/socketsupply/socket/pull/329

**Comment by mribbons** [comment]
@jwerle This still needs some work:

```bash
npm i @socketsupply/socket -g --registry=$NPM_CONFIG_REGISTRY
app; cd app
rm -rf *
ssc init
/home/test/node-v18.15.0-linux-x64/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/bin/ssc: error while loading shared libraries: libwebkit2gtk-4.1.so.0: cannot open shared object file: No such file or directory
```

I realise this is a #329 is a first cut, but we also want to detect missing deps at `install.sh` time, rather than prompting the user to install missing deps one at a time.
