### ISSUE TITLE
installation with curl kills the terminal on Ubuntu 23.04

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#369]
When I run `. <(curl -s -o- https://socketsupply.co/sh)`, it just closes the terminal, nothing happens

**Comment by chicoxyzzy** [comment]
same happens on other terminals (tested on Guake)

**Comment by lamiazar** [comment]
> When I run . <(curl -s -o- https://socketsupply.co/sh), it just closes the terminal, nothing happens
I was experiencing the same problem, I mentioned that  in the 
#339 issue cc @mribbons 
<img width="648" alt="Capture" src="https://user-images.githubusercontent.com/79177582/233868053-147ddebe-b014-42f3-be49-390fff09bc19.PNG">
@chicoxyzzy but after I run the new `curl` command multiple times it worked.

**Comment by lamiazar** [comment]
@mribbons did the `fte` again in ubuntu with `curl` and it's the same issue the terminal closes every time I hit `enter`

**Comment by lamiazar** [comment]
https://user-images.githubusercontent.com/79177582/234124069-f7dd1f5f-ab15-4f99-a2bc-d0c1577f532b.mp4

cc @jwerle @mribbons

**Comment by jwerle** [comment]
Depends on https://github.com/socketsupply/socketsupply.co/pull/222

**Comment by lamiazar** [comment]
I tested this and it's fixed-Can we close this issue @chicoxyzzy ?
