### ISSUE TITLE
Option to chose `androidSdkVersion`

### ISSUE THREAD

**Issue by AndersCan** [socketsupply/socket#376]
I have an android device with Android 10 ([sdk 29](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)) and after running `ssc build -r --platform=android` my app instantly crashes without any error message (it just closes the app).

I managed to find the error via logcat:

```
FATAL EXCEPTION: main
Process: com.beepboop, PID: 28180
java.lang.NoSuchMethodError: No virtual method readAllBytes()[B in class Ljava/io/InputStream; or its super classes (declaration of 'java.io.InputStream' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at com.beepboop.Window$load$1.invoke$lambda-1(window.kt:52)
	at com.beepboop.Window$load$1.$r8$lambda$WON7Zr_yynrwXTCfTi4QN7SEygE(Unknown Source:0)
	at com.beepboop.Window$load$1$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

Found this [SO](https://stackoverflow.com/questions/75837081/android-app-crashes-no-virtual-method-readallbytes) answer that suggests this is due to Android 10 not having Java 9.

The error does not occur if I try to run it on a device with Android 13. 

Tested with https://github.com/socketsupply/socket-examples/tree/master/advanced/vite-vue-ts and I used the fix in https://github.com/socketsupply/socket/pull/354 to avoid https://github.com/socketsupply/socket/issues/348

**Comment by mribbons** [comment]
Thanks for the info @AndersCan.

The SO post was close but not quite right.

I have modified `src/andriod/window.kt` as follows to resolve the error you reported on Android 29.
```diff
--- a/src/android/window.kt
+++ b/src/android/window.kt
@@ -1,6 +1,7 @@
 // vim: set sw=2:
 package __BUNDLE_IDENTIFIER__
 import java.lang.ref.WeakReference
+import android.os.Build
 
 open class Window (runtime: Runtime, activity: MainActivity) {
   open protected val TAG = "Window"
@@ -49,7 +50,12 @@ open class Window (runtime: Runtime, activity: MainActivity) {
           addJavascriptInterface(userMessageHandler, "external")
           val assetManager = runtime.configuration.assetManager
           val indexFile = assetManager.open(filename)
-          val indexBytes = indexFile.readAllBytes()
+          val indexBytes = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
+              indexFile.readAllBytes()
+          } else {
+              indexFile.readBytes()
+          }
```

I also made a couple of changes to support an `ANDROID_PLATFORM` environment variable, instead of the hardcoded `33` value.

I have pushed the necessary changes:
https://github.com/socketsupply/socket/tree/android-platform-env-var

Unfortunately though, there are still some issues, but the one I don't think we can beat on `29` is this:
```bash
04-25 14:53:48.976  8266  8266 I chromium: [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://appassets.androidplatform.net/assets/' was loaded over HTTPS, but requested an insecure script 'socket:test/context'. This request has been blocked; the content must be served over HTTPS.", source: https://appassets.androidplatform.net/assets/ (0)
```
So it looks as though WebView on Android 29 doesn't support custom schemes, which is something we rely on quite heavily.

@chicoxyzzy @jwerle Android 30 almost works, but anything with newer syntax fails: 
```
||=
??=
#function() {}
```
I'm guessing things might work with some transpiling, but this is outside my skill set.

**Comment by chicoxyzzy** [comment]
> @chicoxyzzy @jwerle Android 30 almost works, but anything with newer syntax fails: 
> ```
> ||=
> ??=
> #function() {}
> ```
Those are supported for a while already, should work fine for at least versions released for a last 2-3 years

**Comment by AndersCan** [comment]
> So it looks as though WebView on Android 29 doesn't support custom schemes, which is something we rely on quite heavily.

I'm not going to pretend I understand this codebase, so sorry if this is all incorrect.

---

It looks like 

```
import "socket:test/context"
```

is being, _sort of_, converted to 
```
import https://appassets.androidplatform.net/assets/sockets/test/context.js
```
by [this](https://github.com/socketsupply/socket/blob/master/src/android/webview.kt#L81)


Would directly importing the url `https://appassets.androidplatform.net/assets/sockets/test/context.js` prevent the `custom schemes` issue?

If so, the DX could be improved by using [importMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). Then you could still have `import "socket:test/context"`, but it would resolve the correct URL in the browser.

**Comment by mribbons** [comment]
Hey @AndersCan,
From what I understand, Android 29 devices are end of life and no longer receiving security updates.

Due to this, we are unable to take this any further.

You are welcome to try to work around the js issues by transpiling at app build time
(see socket.ini / [build] / script - This is a user defined command that can be used to pull together any js or other assets, eg:
socket.ini:
```ini
[build]
script = node build.js
```
You can find an example of this by using `npx create-socket-app react-ts`.

To build for a specific android branch:
```bash
git clone https://github.com/socketsupply/socket
cd socket
git checkout android-platform-env-var
# bash
ANDROID_PLATFORM=29 VERBOSE=1 ./bin/install.sh
cd ~/myapp
ANDROID_PLATFORM=29 ssc build -r -o --platform=android
# powershell
$env:ANDROID_PLATFORM=29; .\bin\install.ps1 -verbose=1
cd $env:HOMEPATH\myapp
ssc build -r -o --platform=android
```
Let us know if you find this branch useful, we might refine it a bit further and then merge it into `master`.

**Comment by AndersCan** [comment]
@mribbons Thanks, I'll try it out later this week 🤞

**Comment by AndersCan** [comment]
@mribbons Was able to test this now and it works 🎉  My app now starts on my phone.

`./bin/install.sh` telling me which tools I needed to `brew install` is such a nice DX 👌 

I'm unsure if me running `ANDROID_PLATFORM=29 VERBOSE=1 ./bin/install.sh` always sets the platform version to `29`, but I could even run `ANDROID_PLATFORM=33 ssc build -r -o --platform=android` and it would still work on my phone. Could be that the check for `(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)` was enough for my phone.

I did not have to change the imports, both of these work:
```js
import { Peer } from "https://appassets.androidplatform.net/assets/socket/peer.js";
import { Peer } from "socket:peer";
```

---

All I need to do now is figure out how to _actually_ use `socket:peer` to get my mac and android talking 😅

**Comment by mribbons** [comment]
Hey, that's great @AndersCan !!
Maybe your phone ships a newer version of WebView than the Android 29 emulator :)

> ./bin/install.sh telling me which tools I needed to brew install is such a nice DX 👌

🙏 

> I'm unsure if me running `ANDROID_PLATFORM=29 VERBOSE=1` ./bin/install.sh always sets the platform version to `29`...

You are correct here. I should have mentioned, the current code doesn't force a rebuild if the `ANDROID_PLATFORM` changes. I think the proper solution here is to build into a folder structure like `lib/android-{$arch}-{$ANDROID_PLATFORM}`.

For now, just clear your android builds if you want to test a different platform level:
```bash
rm -rf build/*android*; ANDROID_PLATFORM=33 ssc build -r -o --platform=android
```

Thanks for the feedback!

**Comment by lamiazar** [comment]
This is `FIXED` but I'll leave it open so it will be useful for others that may experience the same issue.

**Comment by lamiazar** [comment]
This is fixed but I'll leave this issue open for future reference.

**Comment by lamiazar** [comment]
This is now Fixed.
