### ISSUE TITLE
Remove `process` dependency from `libsodium.js` file

### ISSUE THREAD

**Issue by getify** [socketsupply/socket#387]
It seems like [this `process` dependency in `libsodium.js`](https://github.com/socketsupply/socket/blob/b11f8ab9e9cba3093597836c08c32a90e6b150e1/api/external/libsodium/index.js#L1) is unnecessary and could instead be replaced with:

```js
const process = {}
```

IOW, it doesn't seem like libsodium actually relies on anything important from node's `process`. If that's indeed true, we should remove this dependency.

**Comment by jwerle** [comment]
`process` is used to detect node and libsodium also uses it to detect node - we want this to work in node too, so we need it

**Comment by getify** [comment]
When I replace the import with just `const process = {}`, our libsodium file works fine in the browser.

IOW, it doesn't seem like libsodium is actually relying on that to use node-specific stuff, or that would break in the browser, no?

In any case, it would be nice if we could find an isomorphic work-around so this file works in a browser.
