### ISSUE TITLE
Localization support for setSystemMenu?

### ISSUE THREAD

**Issue by magicp0tato** [socketsupply/socket#444]
Hello Socket team,

Currently, the setSystemMenu function relies on hardcoded English strings for menu items, making it difficult to localize the menu or customize it with different actions. To enhance its flexibility and support localization, it would be helpful to update the function to accept a JSON object containing menu items, actions, and shortcuts.

A possible JSON structure for this configuration is as follows:

```json
{
  "My Super App Name": [
    {
      "name": "About My Super App",
      "shortcut": "",
      "action": "orderFrontStandardAboutPanel:"
    },
    {
      "type": "separator"
    },
    {
      "name": "Hide",
      "shortcut": "h",
      "action": "hide:"
    },
    {
      "name": "Hide Others",
      "shortcut": "H + Option",
      "action": "hideOtherApplications:"
    },
    {
      "type": "separator"
    },
    {
      "name": "Quit",
      "shortcut": "q",
      "action": "terminate:"
    }
  ],
  "Edit": [
    {
      "name": "Undo",
      "shortcut": "z",
      "action": "menuItemSelected:"
    },
    {
      "name": "Redo",
      "shortcut": "Z + CommandOrControl",
      "action": "menuItemSelected:"
    },
    {
      "type": "separator"
    },
    {
      "name": "Cut",
      "shortcut": "x",
      "action": "cut:"
    },
    {
      "name": "Copy",
      "shortcut": "c",
      "action": "copy:"
    },
    {
      "name": "Paste",
      "shortcut": "v",
      "action": "paste:"
    },
    {
      "name": "Delete",
      "shortcut": "_",
      "action": "delete:"
    },
    {
      "type": "separator"
    },
    {
      "name": "Select All",
      "shortcut": "a",
      "action": "selectAll:"
    }
  ],
  "Other": [
    {
      "name": "Apple",
      "shortcut": "_",
      "action": "menuItemSelected:"
    },
    {
      "name": "Another Test",
      "shortcut": "T",
      "action": "menuItemSelected:"
    },
    {
      "name": "Im Disabled",
      "shortcut": "I",
      "enabled": false,
      "action": "menuItemSelected:"
    },
    {
      "name": "Some Thing",
      "shortcut": "S + Meta",
      "action": "menuItemSelected:"
    }
  ]
}
```

This JSON object would allow users to define their own menu items, actions, and shortcuts in any language. Furthermore, it would support custom actions that can be bound to specific effects, such as binding the "Copy" action to the edit effect. In this way, passing a specific action identifier would trigger the associated effect.

By implementing these changes, we can make setSystemMenu more versatile and user-friendly, allowing for better customization and localization support.

Thank you for considering

**Comment by chicoxyzzy** [comment]
`application.setSystemMenu` does support custom menu item labels
https://github.com/socketsupply/socket/blob/bfcb21dfe7df7ed1878ad94cbb652e2d39202b8b/api/application.js#L184-L204

**Comment by heapwolf** [comment]
You can use any javascript localization library.
