### ISSUE TITLE
Persistent Prompt to Install Android Dependencies

### ISSUE THREAD

**Issue by magicp0tato** [socketsupply/socket#445]
Hello Socket team,

When building with Socket Supply, I'm consistently prompted to install Android build dependencies, despite always responding 'No'. The tool suggests using 'export NO_ANDROID=1' to avoid this prompt in the future, however, this does not appear to work as the prompt still shows up in subsequent builds.

Here is the console output:

```
beam-desktop % NO_ANDROID=1 ssc build -r --port=3000
warn - using '/usr/bin/clang++' as CXX
mv: rename /var/folders/gw/.../T/tmp.... [**translocation**] to /usr/local/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-darwin-arm64/.ssc.env: Permission denied
# Determining default Android search paths.
ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
# Determining Android paths.
warn - Ignoring system java selector (/usr/bin/javac)
warn - Ignoring system java selector (/usr/bin/javac)
mv: rename /var/folders/gw/.../T/tmp... [**translocation**] to /usr/local/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-darwin-arm64/.ssc.env: Permission denied
Do you want to install Android build dependencies?
Download size: 5.5GB, Installed size: 12.0GB [y/N]
> n
warn - You have elected to not install Android dependencies.
**warn - You can use 'export NO_ANDROID=1' to avoid this prompt in the future.**
• WARNING: $CXX env var not set, assuming defaults +0ms
• cleaned: /Users/magic/Desktop/beam-desktop/build/mac +5ms
```

As you can see, despite setting 'NO_ANDROID=1', the prompt to install Android dependencies still appears. This is a minor but persistent inconvenience that interrupts the flow of the build process.

I would greatly appreciate any assistance on resolving this issue, or suggestions on how to properly set the 'NO_ANDROID' environment variable to avoid this prompt.

Thanks

**Comment by mribbons** [comment]
Hello @magicp0tato,
The intended design is for this prompt to only display during build or setup phases, or if the user runs `ssc setup --platform=android`

Please provide the output from:
```
ssc -version
```
And identify how you installed ssc, eg built from source or via npm.

**Comment by mribbons** [comment]
Thanks @magicp0tato,
I just saw the issue in your output:
```bash
mv: rename /var/folders/gw/.../T/tmp.... to /usr/local/lib/node_modules/@socketsupply/socket/node_modules/
@socketsupply/socket-darwin-arm64/.ssc.env: Permission denied
```
On first run, `ssc` should create a `.ssc.env`.
The next time it runs, it won't rerun the First Time Experience process because `.ssc.env` is there.
In your case, `.ssc.env` isn't being created because by default `node_modules` is owned by root on macos.

You can fix it for now as follows:
```bash
sudo /usr/local/lib/node_modules/@socketsupply/socket/node_modules/
@socketsupply/socket-darwin-arm64/.ssc.env
```
We have instructions for resolving the npm issue here: 
https://socketsupply.co/guides/#npm-permissions

cc @lamiazar Can we think about moving this to https://socketsupply.co/guides/#install?

**Comment by lamiazar** [comment]
> cc @lamiazar Can we think about moving this to https://socketsupply.co/guides/#install?

yes, will do.

**Comment by mribbons** [comment]
Thanks @lamiazar.
