### ISSUE TITLE
`app.backend.open()` doesn't reject the promise and doesn't print the error

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#449]
We should throw when backend process fails to start

**Comment by chicoxyzzy** [comment]
it's possible to get an error with `window.addEventListener('process-error', console.log)`

To reject a promise in JS we need to refactor the native `Process` class.

**Comment by chicoxyzzy** [comment]
Currently `process->open()` only can return a `pid`, probably we need it to return `stdout` and `stderr` as well so `json` in `window->resolvePromise(seq, ERROR_STATE, json)` would be available.

cc @jwerle @heapwolf is this correct solution for the problem?

**Comment by chicoxyzzy** [comment]
We also have `process->status`, so maybe it's better to add `process->statusText`

**Comment by chicoxyzzy** [comment]
Changes in the `Process` can also affect extensions' processes

**Comment by jwerle** [comment]
@chicoxyzzy checking if `process->open() > 0` will determine if the process opened successfully

**Comment by chicoxyzzy** [comment]
I want to have the error text on the JS side

**Comment by jwerle** [comment]
> I want to have the error text on the JS side

you can use `errno` with `strerror()`:

```c
const char* message = strerror(errno);
```

If you introduce a `String statusText` property, this can be set in `Process::open()`:

```c++
this->statusText = strerrror(errno);
```

You will need to do this in `src/process/unix.cc` and `src/process/win.cc`

**Comment by heapwolf** [comment]
this api has been deprecated
