### ISSUE TITLE
Ubuntu 20 / libwebkit2gtk-4.0-dev

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#453]
We have had several requests for help with building apps on `ssc` on Ubuntu 20.

To date, most of our efforts have focused on working with libwebkit2gtk-4.1-dev. 

While we did spend some time testing libwebkit2gtk-4.0-dev, we came to the conclusion that it may be unstable - This is a big maybe, more testing is required.

For the near term, libwebkit2gtk-4.0-dev is out of scope for Socket Runtime, but we do recognize that we need to put some time into it.

Therefore, below are the instructions for setting up a Ubuntu 20 environment to build and patch the socket runtime using libwebkit2gtk-4.0-dev.

This will enable any interested community members to get started with Socket Runtime until we have time to revisit libwebkit2gtk-4.0-dev.

Because of the way socket npm packages are structured, we can't provide an npm package that supports libwebkit2gtk-4.0-dev at this time.

Instructions:
```bash
# Required for gcc 11
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install -y gcc-11 g++-11 \
  build-essential \
  clang-12 \
  libc++-dev \
  libwebkit2gtk-4.0-dev \
  autoconf \
  make \
  pkg-config \
  libtool \
  curl

git clone https://github.com/socketsupply/socket
cd socket
git apply <(curl -s -o- https://gist.githubusercontent.com/mribbons/d1bd86fc485e109e5d4666b57c887e39/raw/fa6590873e3bff0887d12ef25205b47fe8a765fe/socket-libwebkitgtk-4.0.dev.diff)
VERBOSE=1 ./bin/install.sh
ssc -v
# You should see something like: 
$ ssc -v 
0.3.0 (45938e45)
mkdir ~/socket-app
cd ~/socket-app
ssc init
# run from a desktop shell
ssc build -r -o
# You should see the Hello World app
```

**Comment by lamiazar** [comment]
@jwerle this is what I'm testing currently(I set up ubuntu 20 and followed all the steps above)
but I was getting multiple errors and the build failed.
