### ISSUE TITLE
(feature request) Add a way to extend/customize native functionality (native plugins)

### ISSUE THREAD

**Issue by pqnet** [socketsupply/socket#473]
## Motivation

As of now the native capabilities that are exposed to the developer is very limited.
This is particularly limiting for mobile platforms, which have sensors and OS integration features that are not available in webviews.

Implementing all APIs and offering with the runtime is a possibility, however
- resources of the core dev group would likely not be enough to cover and support all APIs of all supported platforms
- a core feature of socket runtime is being lightweight, adding lot of functionality by default to the core library is very likely going to affect that

## Proposal
Add a plugin system to allow developers to expose custom native functionality to Javascript. Ideally:
- adding/removing plugins from a project should not require recompiling socket runtime
- implementing functionality for plugins should be allowed in the first class languages for the platform (such as java/kotlin for android and swift/objc for ios)
- plugins should support a package management system (e.g. `npm`) to easily share them among the community

## References
Similar systems have embraced this approach as well:
[plugins in Capacitor](https://capacitorjs.com/docs/plugins)
[plugins in React Native](https://reactnative.directory/)

**Comment by mribbons** [comment]
Hi @pqnet,
Great request, thanks.

@jwerle and I have actually been working on competing prototypes for this over the last week.

We'll review your info and use it to inform the design.

No timeframe yet, we'll ping you when this issue when there's something to test.

**Comment by jwerle** [comment]
This is now possible with #482 and it is in master now.
We'll have a new release next week to make it more widely available
