### ISSUE TITLE
`ssc setup --platform=windows` command fails with `not ok - unable to install clang++.`

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/socket#480]
[socket_install_ps1.log](https://github.com/socketsupply/socket/files/11647670/socket_install_ps1.log)

**Comment by mribbons** [comment]
Confirming that this is caused by the version check not accepting exactly equal versions.

**Comment by mitch1009** [comment]
I had the same problem today 17th June 2023, i solved it by installing the dependency using Visual Studio installer. by default the installer does not select clang++ you can do that by selecting the C++ clang option manually:
![image](https://github.com/socketsupply/socket/assets/66210356/208c6c2f-c625-47f8-ba2b-b0954765fcdc)

**Comment by lamiazar** [comment]
@mitch1009 Thank you, but this is the first step I took to fix the issue, and also getting other errors besides the `clang` issue, I will work on this issue this week.
![Capture](https://github.com/socketsupply/socket/assets/79177582/e7767b01-c976-4b2b-952c-8d2119ec4ba8)

**Comment by lamiazar** [comment]
> Confirming that this is caused by the version check not accepting exactly equal versions.

My issue with `clang` is fixed, I checked the dependency on Visual Studio installer, but the issue is that it's not equal to the required version which is v15, after I updated VS the issue was fixed.
But now I'm getting an error with `exception` when I try to build the app( `ssc build -r` )

**Comment by lamiazar** [comment]
> I checked the dependency on Visual Studio installer, but the issue is that it's not equal to the required version which is v15
This ^ can be checked on https://socketsupply.co/guides/ -->Troubleshooting-->Windows-->Development Environment

**Comment by lamiazar** [comment]
After I removed the cache and build again, the error about `exception` is now gone, and I'm able to build the app
