### ISSUE TITLE
localStorage is null on android build

### ISSUE THREAD

**Issue by Ruulul** [socketsupply/socket#490]
### What OS are you using (`uname -a`, or Windows version)?
Windows 11, i7 x64

### What programming language are you using (C/C++/Go/Rust)?
Javascript

### What did you expect to see and what you saw instead?
Acessing `localStorage` should return a simple key-value storage option, but instead returns `null`

**Comment by jwerle** [comment]
Looks like we need to enable explicitly!

https://developer.android.com/reference/kotlin/android/webkit/WebSettings#setDomStorageEnabled(kotlin.Boolean)

**Comment by jwerle** [comment]
this is now fixed
