### ISSUE TITLE
Create socket app not working

### ISSUE THREAD

**Issue by gowram** [socketsupply/socket#494]
### Create socket app not working in Windows, Ubuntu

I tried to create new app using v0.3.3 whereas it's not working as expected

Node: v14.21.3
npm: 6.14.18
Ubuntu: 22.04.2 

![Screenshot from 2023-06-18 16-35-30](https://github.com/socketsupply/socket/assets/551819/971e77cd-3f5a-47e1-b7d3-3bb8bd1ba35c)

### What did you expect to see and what you saw instead?

it should complete new app creation.

**Comment by heapwolf** [comment]
Node `14.21.3` is no longer supported by the node.js project, are you not able to upgrade to a supported version for some reason (LTE for example)?
