### ISSUE TITLE
path.resolve throws under nodejs

### ISSUE THREAD

**Issue by missinglink** [socketsupply/socket#500]
### What OS are you using (`uname -a`, or Windows version)?

Darwin mac 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:29:26 PDT 2023; root:xnu-8796.121.3~8/RELEASE_ARM64_T8112 arm64

### What programming language are you using (C/C++/Go/Rust)?

JS via node

### What did you expect to see and what you saw instead?

The `path.resolve()` function throws due to `Path.cwd` returning what appears to be a non-string value.
Digging a little deeper it may be due to the `primordials` (specifically `cwd` not being set correctly for nodejs).

```
npm i @socketsupply/socket

cd node_modules/@socketsupply/socket

grep version package.json
  "version": "0.3.3",
```

```
node
Welcome to Node.js v20.3.1.

> const path = await import('./path.js')
undefined

> path.resolve('a', 'b')
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Path.cwd (file:///private/tmp/node_modules/@socketsupply/socket/path/path.js:49:16)
    at cwd (file:///private/tmp/node_modules/@socketsupply/socket/path/posix.js:19:15)
    at Module.resolve (file:///private/tmp/node_modules/@socketsupply/socket/path/posix.js:28:32)
```

**Comment by heapwolf** [comment]
this isn't really intended to work in node, but it might be possible to get it working in node

**Comment by lamiazar** [comment]
Closing-->https://github.com/socketsupply/socket/issues/500#issuecomment-1634100542
