### ISSUE TITLE
When executing `pnpm start` for the second time, scc.js file is missing

### ISSUE THREAD

**Issue by zfangqijun** [socketsupply/socket#507]
### What OS are you using (`uname -a`, or Windows version)?

Darwin MacBook.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### What did you expect to see and what you saw instead?

When executing pnpm start for the second time, scc.js file is missing.

Every time you start, you need to execute `pnpm add -g @socketsupply/socket` again.

```
fangqijun@MacBook todomvc % pnpm start

> todomvc@0.1.0 start /Users/fangqijun/mycode/socket-examples/basic/todomvc
> ssc build -r

• cleaned: /Users/fangqijun/mycode/socket-examples/basic/todomvc/build/mac +9ms
• preparing build for mac +4ms
• package prepared +9ms
• compiled native binary +1247ms
• Running App: /Users/fangqijun/mycode/socket-examples/basic/todomvc/build/mac/todomvc-dev.app +13ms
^C• App result: 2 +2171ms
 ELIFECYCLE  Command failed.

fangqijun@MacBook todomvc % pnpm start

> todomvc@0.1.0 start /Users/fangqijun/mycode/socket-examples/basic/todomvc
> ssc build -r

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/Users/fangqijun/Library/pnpm/global/5/node_modules/@socketsupply/socket/bin/ssc.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
fangqijun@MacBook todomvc % 
```

node version: 18.16.0
pnpm version: 8.5.1

**Comment by lamiazar** [comment]
@zfangqijun Thank you very much for reporting this issue, we did spend some time testing `pnpm` but we had some issues. Currently `pnpm` is out of scope for installing `socket runtime`, but we will put some time into it in the future.

**Comment by garth** [comment]
pnpm is listed in the getting started guides (https://socketsupply.co/guides/#package-manager-or-source) and is just about the only package manager that reliably supports large projects without consuming vast amounts of disk space and cpu cycles.

What alternatives are currently supported?

**Comment by lamiazar** [comment]
> pnpm is listed in the getting started guides (https://socketsupply.co/guides/#package-manager-or-source

@garth we are working on a big update for our website and as I mentioned here https://github.com/socketsupply/socket/issues/507#issuecomment-1653475429 we currently don't support  `pnpm` but you can alternatively use `npm` or install from source(with `curl` or `iwr`).
You can also install from [Create Socket App](https://github.com/socketsupply/create-socket-app).
