### ISSUE TITLE
The process keeps running after I close the app's window

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/socket#508]
I was testing creating an app with `npx create-socket-app` and also the simulator but after I closed the app's window, the process is still running on my terminal
<img width="922" alt="Screenshot 2023-04-27 at 7 48 05 AM" src="https://user-images.githubusercontent.com/79177582/234858237-be48719a-1972-4767-b75b-3475269f1d1c.png">
I had to do `ctrl+c` to exit

**Comment by chicoxyzzy** [comment]
Is this reproducible on Windows and Linux?
