### ISSUE TITLE
Suggestion: ssc init should warn when run on a non-empty directory

### ISSUE THREAD

**Issue by WesSouza** [socketsupply/socket#51]
I ran `ssc init` without realizing it would put files in the current directory (and ask for a project name like many other init commands do).

Running it in a folder with contents should ask the user before creating files.

**Comment by chicoxyzzy** [comment]
@heapwolf I remember you was opposed to make `ssc` accept user input, but I think this case makes sense.

**Comment by WesSouza** [comment]
@chicoxyzzy it could also fail and require a flag like `--force`.

**Comment by heapwolf** [comment]
Yeah I prefer it to fail, +1 on `--force`, PR welcome!

**Comment by algoexpertac** [comment]
Hi, @chicoxyzzy & @heapwolf  I'd love to take this one, can do it over the weekend if possible?

**Comment by iamfotx** [comment]
Hi, @chicoxyzzy & @heapwolf I'd love to take this one, can do it over the weekend if possible?

**Comment by chicoxyzzy** [comment]
This was fixed in #239 in a bit different way. `ssc init` warns instead of trying to replace files
