### ISSUE TITLE
Local install instructions

### ISSUE THREAD

**Issue by Wehzie** [socketsupply/socket#512]
How would it be possible to install the `ssc` command line tool without installing the package globally via `npm i @socketsupply/socket -g`? On most Linux hosts this will require `sudo` privileges.

I'm on linux and have attempted the following
```
mkdir path/to/project
cd path/to/project
npm init
npm i @socketsupply/socket
mkdir subfolder
cd subfolder
npx create-socket-app vanilla
```
this fails because `ssc` cant be called and no .ini file is created

Further I tried installing in
```
mkdir ~/npm
cd npm
npm i @socketsupply/socket
```
and adding to path with `export PATH="$PATH:$HOME/npm/bin"`

I would like to avoid global installs as otherwise `ssc build -r --port=8000` also seems to need `sudo` privileges.

**Comment by chicoxyzzy** [comment]
You can install it without the `-g' flag: 'npm i @socketsupply/socket`. `ssc` command will be available in the `scripts` section in `package.json`. It will also be available from the command line via `./bin/ssc` inside of the project root directory.

**Comment by chicoxyzzy** [comment]
Another way is to install `ssc` with `curl -s -o- https://socketsupply.co/sh | bash`

**Comment by chicoxyzzy** [comment]
Seems like the question is answered. Please let me know if proposed solutions didn't help.

**Comment by chicoxyzzy** [comment]
Notice that the recommended way to install via `curl` is now `. <(curl -s -o- https://socketsupply.co/sh)`
