### ISSUE TITLE
iOS app isn't working on create-socket-app

### ISSUE THREAD

**Issue by tanishqkancharla** [socketsupply/socket#525]
### What OS are you using (`uname -a`, or Windows version)?
Darwin Tanishqs-MacBook-Pro-2.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64

arm64

### What programming language are you using (C/C++/Go/Rust)?
JS? Whatever create-socket-app initializes with.

### What did you expect to see and what you saw instead?
Repro:
* Init: `npx create-socket-app`
* Run ios build and run step: `ssc build --platform=ios-simulator -r`

Expected:
* "Hello, iOS" or something similar

Seen:
* Blank white screen. Loaded initial html correctly but javascript didn't run:
<img width="806" alt="CleanShot 2023-08-12 at 22 59 00@2x" src="https://github.com/socketsupply/socket/assets/31808124/9c8a8c56-1b32-4e88-919e-3e28c095db04">

**Comment by tanishqkancharla** [comment]
Specifying `--port=3000` in build and run command doesn't work either, just loads the white screen and crashes immediately (returning the simulator to the home screen, terminates console process)

**Comment by tanishqkancharla** [comment]
Desktop build works fine, says "Hello, darwin".

**Comment by lamiazar** [comment]
@tanishqkancharla IOS app is now working as @chicoxyzzy mentioned here 
https://discord.com/channels/775715380089716778/775715380572323861/1141492036780953600
If you are experiencing any issues follow the steps here 
https://discord.com/channels/775715380089716778/775715380572323861/1141492036780953600
Please let us know if you have any other questions.

**Comment by tanishqkancharla** [comment]
That worked! Thanks.
