### ISSUE TITLE
ENV vars defined in socket.ini always come in as '' when undefined

### ISSUE THREAD

**Issue by bcomnes** [socketsupply/socket#528]
ENV vars that are configured in socket.ini always come in as a blank string when they are non set. They should resolve to `undefined` unless there is a reason not to.

**Comment by chicoxyzzy** [comment]
@bcomnes what do you mean by "not set"?

**Comment by chicoxyzzy** [comment]
Unix env variables always have a value, so maybe we should throw an error if it's not set

**Comment by chicoxyzzy** [comment]
or maybe print a warning and assign `1` or an empty string

**Comment by chicoxyzzy** [comment]
oh it's already `''`, so I think this is correct behavior

**Comment by bcomnes** [comment]
To clarify:

Say you have a socket app that pulls in the `FOO` env var. 

When you run `FOO=whatever socket build -r`, then `process.env.FOO === 'whatever'`.

If you run `socket build -r` then `process.env.FOO === ''`. It's true that `''` coerces to false, it seems more correct to me that `process.env.FOO === undefined`. 

Perhaps `FOO="" socket build -r` would result in `process.env.FOO === ''`, but it seems like we should leave undefined ENV vars as undefined, and not an empty string to better match the expectations on the JS side.

**Comment by lamiazar** [comment]
@bcomnes what's the status of this issue? is it still `wip`?

**Comment by bcomnes** [comment]
Don't think it's been started yet.

**Comment by lamiazar** [comment]
> Don't think it's been started yet.

I will change the status, thx
