### ISSUE TITLE
Improve testing experience

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#53]
Currently we use https://github.com/socketsupply/ssc-test to add test script to the document's `<head>`

We can implement feature in the Socket Runtime, so developers don't have to add an extra dependancy. Also test files don't need to be in the production bundle. That should be implemented as a condition in the build script.

`ssc build --test=test.js` should:
- copy test files to the `<builddir>/<os>/<name>-dev.app` (that's the task for a build script, nothing to do here)
- inject the `test.js` script on `ssc build -r --test=test.js` or `ssc run --test=test.js`
- ...or warn when there's no `test.js` file in the resources directory

One thing I'm not sure is whether should a value for the `--test` option be mandatory (currently it's not)

**Comment by chicoxyzzy** [comment]
cc @nichoth

**Comment by chicoxyzzy** [comment]
> inject the test.js script

this way we can run a separate test or the whole test bundle (file, which imports all the test files)

**Comment by chicoxyzzy** [comment]
Oh, we probably should also inject https://github.com/socketsupply/ssc-test/blob/main/src/test-context.js as well. Do we always need to patch console or only in headless mode?

**Comment by nichoth** [comment]
> Oh, we probably should also inject https://github.com/socketsupply/ssc-test/blob/main/src/test-context.js as well. Do we always need to patch console or only in headless mode?

Currently we always patch console. Not sure how required that is.

**Comment by nichoth** [comment]
> Currently we use https://github.com/socketsupply/ssc-test to add test script to the document's `<head>`
> 
> We can implement feature in the Socket Runtime, so developers don't have to add an extra dependancy. Also test files don't need to be in the production bundle. That should be implemented as a condition in the build script.
> 
> `ssc build --test=test.js` should:
> 
> * copy test files to the `<builddir>/<os>/<name>-dev.app` (that's the task for a build script, nothing to do here)
> * inject the `test.js` script on `ssc build -r --test=test.js` or `ssc run --test=test.js`
> * ...or warn when there's no `test.js` file in the resources directory
> 
> One thing I'm not sure is whether should a value for the `--test` option be mandatory (currently it's not)

Currently we have this as part of `ssc-test`, meant to be used in your build script.

```js
 if (!buildTests.isTest()) return

    const testDir = path.join(__dirname, '/test')
    // (test-dir, output-dir)
    await buildTests(testDir, target)
```

**Comment by chicoxyzzy** [comment]
Yes, I see. Although, build script is not necessary a JS file. I think we can move this part to the `-base-cli`

**Comment by heapwolf** [comment]
why not do all your javascript assembly first and then pipe it to socket `esbuild ... | ./my-app --stdin | tap-out`

**Comment by chicoxyzzy** [comment]
> why not do all your javascript assembly first and then pipe it to socket `esbuild ... | ./my-app --stdin | tap-out`

It could be unobvious how to set it all up. We only patch console in `io`, so the output is not visible by default without `ipc://stdout` / `ipc://stderr`. I want to add the absolute minimum necessary code in the https://github.com/socketsupply/socket/pull/56 to make it just work

**Comment by chicoxyzzy** [comment]
every test file in the `--test=<file>` requires `import '@socketsupply/io/runtime.js'` which looks too unintuitive. We always want to patch a console

**Comment by nichoth** [comment]
Documented an issue with test mode — https://github.com/socketsupply/socket-examples/issues/58
