### ISSUE TITLE
I think the docs are a little confusing about what Socket do

### ISSUE THREAD

**Issue by Noriller** [socketsupply/socket#552]
I heard about the project in the LogRocket podcast and loved the idea.
And from what I understood, you have one part that is the cross platform build and other that is the P2P.

For me and a lot of people, the cross platform, if it works for their case would be HUGE. Probably more important the P2P part, but some of my first questions is if I need the P2P in order to use the cross platform build and if I have something made in a fullstack framework like Next, Nuxt, SvelteKit... can I use it? How and what are the pitfalls?

For the P2P part it goes into technical details too fast. Don't get me wrong, I like it, but for someone used to the old web2 way of doing things with a server, something I understand better, I would like the docs to work with me for something like refactoring a common server handle into a P2P telling me differences, pros and cons. Maybe adding how to integrate it to an existing app.
I feel like all the technical part should be like an "extra". As in, giving the overview concepts and redirecting to the more in depth content "if you want to know more".

**Comment by lamiazar** [comment]
> I would like the docs to work with me for something like refactoring a common server handle into a P2P telling me differences, pros and cons. Maybe adding how to integrate it to an existing app.
I feel like all the technical part should be like an "extra". As in, giving the overview concepts and redirecting to the more in depth content "if you want to know more".

@Noriller Thank you for your suggestions, we are still working on the `p2p` docs, significant updates are coming soon.
