### ISSUE TITLE
Cannot install Socket runtime using curl

### ISSUE THREAD

**Issue by yashdiniz** [socketsupply/socket#563]
### What OS are you using (`uname -a`, or Windows version)?
Linux 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What version Socket Runtime are you using?
Error occurs when running `. <(curl -s -o- https://socketsupply.co/sh)`, so I haven't installed the Socket runtime yet.

### What did you expect to see and what you saw instead?
**Expected**: successful installation

**Observed**: 
```
#   __   ___  ___      ___ ____
#  /__  /  / /   /_/  /__   /
#  __/ /__/ /__ /  \ /__   /
#
# getting files...
warn - using '/home/yash/.local/share/socket' as SOCKET_HOME
warn - Installing to '/usr/local'
/home/yash/socket/bin/functions.sh: line 499: /usr/share/fish/completions/clang++.fish: Permission denied
warn - using '/usr/share/fish/completions/clang++.fish' as CXX
# Determining default Android search paths.
ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
# Determining Android paths.
# Using found javac /home/yash/.local/bin/jdk-19.0.2/bin/javac
ok - Found gradle (/home/yash/.gradle/gradle-8.0.2)
ok - Found JAVA_HOME (/home/yash/.local/bin/jdk-19.0.2)
ok - Found GRADLE_HOME (/home/yash/.gradle/gradle-8.0.2)
ok - Found ANDROID_HOME (/home/yash/Android/Sdk)
ok - Found sdkmanager (cmdline-tools/latest/bin/sdkmanager)
# Determining default Android search paths.
ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
# Installing Android SDK manager.
# Installing JDK.
# Installing Gradle.
Do you want to automatically accept all Android SDK Manager licenses? [y/N]
> y
# Ensuring Android dependencies are installed
[=======================================] 100% Computing updates...

[=======================================] 100% Computing updates...
All SDK package licenses accepted.

# checking compiler features
./bin/install.sh: line 872: /usr/share/fish/completions/clang++.fish: Permission denied
./bin/install.sh: line 877: /usr/share/fish/completions/clang++.fish: Permission denied
not ok - /usr/share/fish/completions/clang++.fish () failed in feature check required for building Socket Runtime - please report (https://discord.gg/YPV32gKCsH)
```

Also, I'm not sure how to use `sudo` in this situation, since `sudo . <(curl -s -o- https://socketsupply.co/sh)` kinda doesn't work...

**Comment by heapwolf** [comment]
I wonder if this is a problem with trying to run this script from `fish` shell, can you try dropping into a bash shell and run the script from there? (just type `bash`, enter, and then try to run `. <(curl -s -o- https://socketsupply.co/sh)` again)

**Comment by yashdiniz** [comment]
**Update**: Tried running the script after uninstalling `fish`. It ran successfully, and `ssc` is now installed!

I tried debugging the issue by checking the script and was able to narrow it down to the `determine_cxx` function in `functions.sh` [here(line 502)](https://github.com/socketsupply/socket/blob/47a53cb17a051f85c8ef9ed3776bc6859d0b6a4b/bin/functions.sh#L502C10-L502C10).

Here's the list of `clang++` executables that get considered by `determine_cxx` when I have `fish` installed:
``` bash
~$ dpkg -S clang 2>&1| grep "clang++" | cut -d" " -f 2 | while read clang; do
        # Convert clang++ paths to path#version strings
        bin_version="$("$clang" --version|head -n1)#$clang"
        echo $bin_version;
      done | sort -r
bash: /usr/share/fish/completions/clang++.fish: Permission denied
#/usr/share/fish/completions/clang++.fish
Ubuntu clang version 14.0.0-1ubuntu1.1#/usr/lib/llvm-14/bin/clang++
Ubuntu clang version 14.0.0-1ubuntu1.1#/usr/bin/clang++-14
Ubuntu clang version 14.0.0-1ubuntu1.1#/usr/bin/clang++
~$ 
```

`fish-common` has a `clang++` completion script that's considered part of this list, which is causing issues.
I made a PR (#579) with one way to fix this issue.

@jwerle, the contribution guidelines say to call out the assignee and inform them about any PR.

**Comment by lamiazar** [comment]
> I made a PR (https://github.com/socketsupply/socket/pull/579) with one way to fix this issue.

@yashdiniz Thank you for your contribution 😊
