### ISSUE TITLE
Document `ssc.config`

### ISSUE THREAD

**Issue by nichoth** [socketsupply/socket#60]
Should have documentation about the file `ssc.config` — what fields are required, etc.

**Comment by chicoxyzzy** [comment]
the documentation is here https://sockets.sh/config/

it needs an update

**Comment by nichoth** [comment]
> the documentation is here https://sockets.sh/config/
> 
> it needs an update

I see, in the foot part. Thanks

<img width="248" alt="image" src="https://user-images.githubusercontent.com/5776508/208145377-8460b7b9-f96f-4b78-a178-488b9e2b82df.png">

**Comment by chicoxyzzy** [comment]
Also `ssc init` creates a config with comments.

There is a PR which renames it to `ssc.conf` https://github.com/socketsupply/socket/pull/59
