### ISSUE TITLE
npm run gen: cannot find package 'acorn' 

### ISSUE THREAD

**Issue by c8e4** [socketsupply/socket#600]
`npm run gen` returns an Error
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'acorn' imported from /Users/xxx/repos/socket/bin/generate-docs.js
```
it seems like **acorn** is missing in devDependencies

(branch master, commit: 62e26b0267d92de06aa04e1ce555b27a2cb0c589)

**Comment by chicoxyzzy** [comment]
it's in the `devDependencies` in the [`package.json`](https://github.com/socketsupply/socket/blob/6f1c7efb77752ab436481fe1b4f9f02644c5693b/package.json#L22). When does this error appear?

**Comment by c8e4** [comment]
cloned repo again, ran `npm run gen` - works fine, apologize for a opening a non issue! can be closed
