### ISSUE TITLE
Feature Request: socket.ini specified "import-map"

### ISSUE THREAD

**Issue by getify** [socketsupply/socket#606]
For certain functionality in web apps that will be packaged as Socket apps, you might want to have two different modules with different implementations (one that works for the web, one that works in Socket), with identical APIs (aka "isomorphic code"), such that your app code is the same regardless of the underlying implementation.

It would be extremely helpful if your Socket config (socket.ini) could specify an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap), by way of a local .json file you include, which would get injected (in HTML form) into your HTML pages (at build-time) to tell the webview to load the different module implementation.

Example:

In my web app, I do `import JSONStore from 'src/lib/json-store.js'`, which is a `localStorage` implementation of the json-store module. For the purposes of my code running in Socket, I want to provide an import-map which remaps `src/lib/json-store.js` to `@socketsupply/json-store`, which is the `fs` backed implementation of the same API.

I need Socket to inject this import-map rather than me including it, because my web app doesn't need that sourcemap at all, only the Socket app instance needs it.

----

One concern to address: what do we do if one or more of the HTML pages already has an import-map in the HTML? you can't have two import-maps, and the webview will only use the first one it finds. So we'd need some way of scanning/parsing the HTML to detect, and if one is there, either merge, or just skip including on that page, or something like that.

**Comment by chicoxyzzy** [comment]
The issue with this is that multiple import maps are not in the HTML spec (yet). If there's one in the `index.html` already, than it's up to the browser how to handle this

**Comment by jwerle** [comment]
I think we can inject an importmap during the runtime preload phase. If one includes an importmap already in their HTML, then the socket importmap injected into the webview is a no-op.
