### ISSUE TITLE
process.exit(1) is exiting 0

### ISSUE THREAD

**Issue by bcomnes** [socketsupply/socket#608]
When I process.exit(1) the process actually exits 0:

```
• Exiting Window#0 (code=1) +105321ms
```

**Comment by chicoxyzzy** [comment]
The output is correct. `Window#0` is a main window, which has index `0`. `(code=1)` is the exit code

**Comment by bcomnes** [comment]
Closed by https://github.com/socketsupply/socket/commit/b6b84856b154f85599ad0ac8d88f65e9a8e3b5ef
