### ISSUE TITLE
setTimeout(fn, 0) is very slow in headless mode

### ISSUE THREAD

**Issue by bcomnes** [socketsupply/socket#610]
When running tests heedlessly, I use setTimeout(fn, 0) as a stand in for requestAnimation frame. The problem I started running into was that these timeouts are taking 10-15 seconds to resolve when run heedlessly. I think this might be a regression.

**Comment by bcomnes** [comment]
Closing for now, since I don't think there is anything we can do here.

**Comment by lamiazar** [comment]
@bcomnes Thanks I was about to ask about it(like an hour ago)
