### ISSUE TITLE
[RFC] 'i18n' API

### ISSUE THREAD

**Issue by jwerle** [socketsupply/socket#631]
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization

It could be quite useful to all a "locales" directory to be configured:

```ini
[locales]
source = "locales" ; relative to app resources
```

or per language

```ini
[locales.en]
source = "locales/en" l relative to app resources
```

where a "locale" directory can contain a `messages.json` file of "gettext" like translations that could look like:

```json
{
  "messageKey": {
    "message": "An English representation of 'messageKey'",
    "description": "An English description of 'messageKey'."
  }
}
```

or

```json
{
  "messageKey": {
    "message": "Une représentation en anglais de 'messageKey'",
    "description": "Une description en anglais de 'messageKey'."
  }
}
```

We could implement [`globalThis.i18n.detectLanguage`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage) based on Google's [CLD](https://github.com/CLD2Owners/cld2) implementation.

The surface of the entire API could have exact parity with:

- [`globalThis.i18n.LanguageCode`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/LanguageCode) A [language tag](https://www.rfc-editor.org/rfc/rfc9110.html#name-language-tags) such as "en-US" or "fr".

- [`globalThis.i18n.getAcceptLanguages()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getAcceptLanguages) Gets the [accept-languages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#the_accept-language_header) of the browser. This is different from the locale used by the browser. To get the locale, use [i18n.getUILanguage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage).

- [`globalThis.i18n.getMessage()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getMessage) Gets the localized string for the specified message.

- [`globalThis.i18n.getUILanguage()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage) Gets the UI language of the browser. This is different from [i18n.getAcceptLanguages](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getAcceptLanguages) which returns the preferred user languages.

- [`globalThis.i18n.detectLanguage()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage) Detects the language of the provided text using the [Compact Language Detector](https://github.com/CLD2Owners/cld2).

**Comment by bcomnes** [comment]
I like it.
