### ISSUE TITLE
Generate default icon in 'ssc init'

### ISSUE THREAD

**Issue by jwerle** [socketsupply/socket#638]
We currently do not generate a default application icon which would be useful

**Comment by chicoxyzzy** [comment]
We are generating it in CSA ([this one](
![](https://github.com/socketsupply/create-socket-app/blob/main/common/src/icon.png)
)), but I agree that we should do it for `ssc init`. @heapwolf should we use the same icon?

**Comment by jwerle** [comment]
> We are generating it in CSA ([this one](https://github.com/socketsupply/create-socket-app/blob/main/common/src/icon.png)), but I agree that we should do it for `ssc init`. @heapwolf should we use the same icon?

yeah lets use it
