### ISSUE TITLE
API for presenting WebKit devtools programmatically

### ISSUE THREAD

**Issue by aleclarson** [socketsupply/socket#668]
There's an unofficial way to programmatically open the WebKit devtools of a `WKWebView` as seen here: https://stackoverflow.com/a/37874205/2228559

It would be useful to me to be able to present this automatically when my app opens in debug mode.

**Comment by heapwolf** [comment]
I got it working here -> https://github.com/socketsupply/socket/blob/9c0978d1ff5791e9789072fb86ba891bd1bb0005/src/window/apple.mm#L1115

**Comment by aleclarson** [comment]
Oh awesome! 🎉
