### ISSUE TITLE
Error — 'name' value is required in socket.ini

### ISSUE THREAD

**Issue by nichoth** [socketsupply/socket#69]
See [branch ipc-cleanup](https://github.com/socketsupply/ssc-test/tree/ipc-cleanup) in `ssc-test`

Running `npm test`, I see
```
    • 'name' value is required in socket.ini +0ms
```

But the `socket.ini` file [does have a `name`](https://github.com/socketsupply/ssc-test/blob/ipc-cleanup/example/socket.ini#L16).

**Comment by heapwolf** [comment]
your file is not valid [ini format](https://en.wikipedia.org/wiki/INI_file)
