### ISSUE TITLE
Allow 'LSMinimumSystemVersion' to be "opt-in" for 'Info.plist' entry

### ISSUE THREAD

**Issue by jwerle** [socketsupply/socket#698]
We should allow this value to be configurable, by opt-in with `socket.ini`, instead of defaulting to `13.0.0`:

```ini
[mac]
minimum_supported_version = 10.10.0
```

**Comment by jwerle** [comment]
cc @aleclarson

**Comment by chicoxyzzy** [comment]
for mac only or for iOS as well?

**Comment by jwerle** [comment]
> for mac only or for iOS as well?

for this issue, just macOS
we currently set `-miphoneos-version-min` and `-mios-simulator-version-min` when compiling prebuilds

**Comment by yassernasc** [comment]
It seems to be [resolved](https://github.com/socketsupply/socket/commit/e8e333643ccbd4f29d358eab9320fb521ae5b331).
