### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain"

### ISSUE THREAD

**Issue by acailly** [socketsupply/socket#703]
### What OS are you using (`uname -a`, or Windows version)?

Windows 11 Pro, x64, Edge Version 118.0.2088.46 64bits

### What version Socket Runtime are you using?

0.4.0 (6409910e)

### What programming language are you using (C/C++/Go/Rust)?

only JS

### What did you expect to see and what you saw instead?

I tried to run the initial example project generated with `npx create-socket-app vanilla` and I have the following errors: 

- Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. (socket/internal/init.js:1)
- Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: socket://internal/init (index.html:1)

When I try to import a JS file by adding `<script src="index.js" type="module"></script>` in the body, I have this error: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. (index.js:1)

I was not expecting MIME type issue on all JS files

**Comment by jwerle** [comment]
We fixed this and it is slated to be in the `v0.5` release coming soon

**Comment by cwiggins999** [comment]
I'm anxiously awaiting this fix as well - just found Socket this morning and looks like a good fit for some things we are doing.

**Comment by lamiazar** [comment]
This issue is fixed.
