### ISSUE TITLE
File System Mounts

### ISSUE THREAD

**Issue by jwerle** [socketsupply/socket#715]
As we move to sandboxing for all applications, we'll need a way to provide file system access with permission from the end-user which Apple makes this possible with [`startAccessingSecurityScopedResource`](https://developer.apple.com/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso?language=objc) and [`bookmarkDataWithContentsOfURL:error:`](https://developer.apple.com/documentation/foundation/nsurl/1408344-bookmarkdatawithcontentsofurl?language=objc) and Widows make it possible with [Windows sandbox configuration](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-configure-using-wsb-file)

## File System Mounts

A mechanism for configuring a mounted file system path on the host that is available to the through the navigator URI at socket://<bundle_identifier>/mnt/<mount>

### `socket.ini` Configuration

```ini
[navigator.mounts]
$HOST_HOME/.local/share/my-app = "user-shared"
$HOST_CONTAINER/shared = "app-shared"
```

The `[navigator.mounts]` section will have access to special variables:

```ini
# The HOME directory of the user host
HOST_HOME = "/Users/jwerle"
# The container directory for the application with respect to the host user 
HOST_CONTAINER = "/Users/jwerle/Library/Containers/com.company.app"
# The working directory of the application process
HOST_PROCESS_WORKING_DIRECTORY = "/Users/jwerle/Applications/My App.app/Contents/MacOS/Resources"
```

The application will mount the paths and make them available in the navigator:

```js
const plugin = await import('/mnt/user-shared/plugin.js')
```

We could provide runtime mounts with an API:

```js
import { mount } from 'socket:application'
await mount('$HOST_HOME/.local/shared/my-app, 'user-shared')
const plugin = await import('/mnt/user-shared/plugin.js')
```

**Comment by bcomnes** [comment]
Am I allowed to create the mount directory if it doesn't exist?

**Comment by bcomnes** [comment]
With the following config in `socket.ini`:

```ini
[navigator.mounts]
$HOST_HOME/.local/relay/plugins = "/relay-plugins"
```

Where the tree of `~/.local/relay/plugins` looks like:

```bash
.
├── plugin-1
│   └── plugin.js
└── plugin-2
    └── plugin.js
```

When I import the following URLs:

```js
await import('/relay-plugins/plugin-2/plugin.js')
```

I get the following errors:

```
TypeError: Importing a module script failed.
```

The terminal reports a 404 network request to `socket://co.socketsupply.relay/relay-plugins/plugin-1/plugin.js`

Are there code-signing requirements needed for this feature to work?

**Comment by bcomnes** [comment]
Oops, looks like the config key was wrong:

```
[webview.navigator.mounts]
```

That works now, but imports are still coming back as empty objects.
