### ISSUE TITLE
Can you please add some detail documentation on Installation?

### ISSUE THREAD

**Issue by TroublesomeSaramsh789** [socketsupply/socket#77]
I watched the talk show at NodeConf EU 2022 and loved the idea so I was here to try it out but was unable to get it set up on my windows machine. 

I followed the instruction but the compilation was unsuccessful. I think i am short on some packages so can you please add some detail instruction and requirements to get it setup?. 

not ok - the build tool failed to compile.

![Powershell Screenshot](https://user-images.githubusercontent.com/54758588/209493783-8f6403b7-aa40-44f7-a815-099229c0e603.png)

**Comment by LeFede** [comment]
Same here. 
Not sure what I'm doing wrong.
+1 to this

**Comment by chicoxyzzy** [comment]
Probably the issue is that you need to [install build tools](https://sockets.sh/troubleshooting/#windows)

We are polishing these parts and will definitely make the errors more human friendly soon!

**Comment by chicoxyzzy** [comment]
Closing as a stale issue
