### ISSUE TITLE
Set default value for 'title' field when missing from 'socket.ini'

### ISSUE THREAD

**Issue by jwerle** [socketsupply/socket#83]
Currently, I see `{{title}}` on my Android device for an app I am testing. It isn't defined in `socket.ini` so this makes sense. Ideally, it should fall back to a default value (`name`) or be a **required** field. `name` currently cannot have white spaces, while `title` is a friendly name that can include white space and be seen by humans. Which SHOULD require both IMO, or issue a warning that we're falling back to `name`.

cc @chicoxyzzy @heapwolf

**Comment by chicoxyzzy** [comment]
We removed `title` from the config recently and use document's `<title>` instead

**Comment by jwerle** [comment]
That is a regression because we still use `{{title}}` in a few places

- Android: https://github.com/socketsupply/socket/blob/master/src/cli/templates.hh#L257
- Linux: https://github.com/socketsupply/socket/blob/master/src/cli/templates.hh#L295
- Windows: https://github.com/socketsupply/socket/blob/master/src/cli/templates.hh#L320 and https://github.com/socketsupply/socket/blob/master/src/cli/templates.hh#L347

`title` was supposed to be a display name (human friendly)

**Comment by jwerle** [comment]
> We removed `title` from the config recently and use document's `<title>` / `window.document.title` for the window name instead

why is this mutually exclusive with the `title` property in `socket.ini`

**Comment by chicoxyzzy** [comment]
I think we should fix this one. Can we allow `name` to have spaces and replace `title` usages by `name`? We can automatically generate the form of `name` without spaces (and other special characters)

**Comment by jwerle** [comment]
I believe name is used for naming the executable and other things that shouldn't/couldn't have white space

**Comment by chicoxyzzy** [comment]
yes, we can have `auto const escapedName = getEscapedName(name)`

**Comment by jwerle** [comment]
I really think `title` and `name` should _both_ be supported, but fall backs can work:

1. IF `title` is defined in `socket.ini`, use it as human friendly/readable application title
  a. IF `name` is _not_ defined in `socket.ini` set `name` to an "escaped" (no spaces or special characters) value of `title` 
3. IF `name` is defined in `socket.ini`, use it as application binary name
  a. IF `title` is _not_ defined in `socket.ini` set `title` to be `name`

If `title` or `name` are defined in `[linux]`, `[mac]`, `[android]`, `[win]`, `[ios]` sections prefer them instead
