### ISSUE TITLE
The start script failed when use create-socket-app

### ISSUE THREAD

**Issue by Priestch** [socketsupply/socket#851]
### What OS are you using (`uname -a`, or Windows version)?

Linux P5560 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What version Socket Runtime are you using?

0.5.3 (c4ef020e)

### What programming language are you using (C/C++/Go/Rust)?

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

go version go1.21.3 linux/amd64

rustc 1.71.0 (8ede3aae2 2023-07-12)

### What did you expect to see and what you saw instead?

I use the create-socket-app to create a demo app, I run `npm run start` after installed the dependencies, it output the error below, What I should to fix it?

```bash
> ssc build -r -o

• cleaned: /home/xx/build/linux +2ms
• preparing build for linux +0ms
• ran user build command +261ms
• package prepared +0ms
• Unable to build +79ms
• In file included from /home/xx/.fnm/node-versions/v16.19.1/installation/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/src/init.cc:1:
/home/xx/.fnm/node-versions/v16.19.1/installation/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/src/core/config.hh:4:10: fatal error: 'iterator' file not found
#include <iterator>
         ^~~~~~~~~~
1 error generated.
 +0ms

**Comment by jwerle** [comment]
hi @Priestch,

could you ensure you have `libc++abi-14-dev` and `libc++-14-dev ` installed?

**Comment by trygve-lie** [comment]
I am getting the same error on Ubuntu (22.04.3).

I'm following the quick start example in the docs: https://socketsupply.co/guides/#quick-start_develop and on `ssc build -r` I am getting:

```sh
$ ssc build -r
• preparing build for linux +3ms
• package prepared +7ms
• Unable to build +527ms
• In file included from /home/trygve/.nvm/versions/node/v20.10.0/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/src/init.cc:1:
/home/trygve/.nvm/versions/node/v20.10.0/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-linux-x64/src/core/config.hh:4:10: fatal error: 'iterator' file not found
#include <iterator>
         ^~~~~~~~~~
1 error generated.
 +0ms
```

> could you ensure you have libc++abi-14-dev and libc++-14-dev  installed?

I do have both installed:

```sh
libc++abi-14-dev is already the newest version (1:14.0.0-1ubuntu1.1).
libc++-14-dev is already the newest version (1:14.0.0-1ubuntu1.1).
```

**Comment by trygve-lie** [comment]
Adding this solved it for me:

```sh
sudo apt install g++-12
```

Based on https://askubuntu.com/a/1449800

**Comment by jwerle** [comment]
> Adding this solved it for me:
> 
> ```shell
> sudo apt install g++-12
> ```
> 
> Based on https://askubuntu.com/a/1449800

ah great! I just noticed you had gcc@11 installed above - we need to update our guides

**Comment by jwerle** [comment]
> > Adding this solved it for me:
> > ```shell
> > sudo apt install g++-12
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Based on https://askubuntu.com/a/1449800
> 
> ah great! I just noticed you had gcc@11 installed above - we need to update our guides

oops, no it is the OP that has gcc@11

@Priestch could you try what @trygve-lie did to resolve the issue?

**Comment by Priestch** [comment]
@jwerle It worked, now I can successfully run the demo.

**Comment by ahouchens** [comment]
> Adding this solved it for me:
> 
> ```shell
> sudo apt install g++-12
> ```
> 
> Based on https://askubuntu.com/a/1449800

Yup, this worked for me too!
