### ISSUE TITLE
With .mjs files, Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html"

### ISSUE THREAD

**Issue by acailly** [socketsupply/socket#852]
### What OS are you using (`uname -a`, or Windows version)?

Windows 11 Pro, x64, Edge Version 120.0.2210.77 64bits

### What version Socket Runtime are you using?

0.5.3 (c4ef020e)

### What programming language are you using (C/C++/Go/Rust)?

only JS

### What did you expect to see and what you saw instead?

This is an issue similar to https://github.com/socketsupply/socket/issues/703

I tried to run the initial example project generated with npx create-socket-app vanilla and changed the `index.js` extension into `index.mjs`

When I do this change, I have this error in the console: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. 

I was not expecting MIME type issue on `.mjs` files

**Comment by chicoxyzzy** [comment]
fixed in https://github.com/socketsupply/socket/pull/854/commits/bbc75ae93eb21bd9c67c8a8f64f75f86d01a8a5c
