### ISSUE TITLE
Can one use socket supply P2P functionality in a react application, independently of the other socket supply functionalities. 

### ISSUE THREAD

**Issue by Joshua-onwuzu** [socketsupply/socket#857]
I am exploring socket supply but only care about it p2p functionalities and i am trying to integrate with a typescript react application, but i am having issues with webpack when i import it like this  `import { network, Encryption } from 'socket:network'` . 

the error says :

`Uncaught Error: Module build failed: UnhandledSchemeError: Reading from "socket:network" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "socket:" URIs.`

this makes me wonder if it can be used independently of the entire socket cross-platform runtime

i already installed `@socketsupply/socket` version `0.5.3` and using react `18.2.0`

**Comment by chicoxyzzy** [comment]
It can't be used in a browser because it uses UDP sockets which are not available in browsers
