### ISSUE TITLE
Document IPC XHR API

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#87]
The `ipc://` API needs to be fully documented. Especially since Windows requires using `http://` instead of `ipc://`.

The `socket-api` repo does exist, but it serves as a complete porcelain API. Not just simple examples of how to use the plumbing IPC commands.

Note: After discussion, it was decided that the IPC XHR API would be kept private for the time being. Making it an officially supported API this early would bring a lot of pain in the future. This should still be documented, but the priority has dropped because of this.

**Comment by jwerle** [comment]
We have it somewhat documented inline in [`bridge.cc`](https://github.com/socketsupply/socket/blob/master/src/ipc/bridge.cc#L50)

something official would be great

**Comment by trevnorris** [comment]
After discussion, it was decided that the IPC XHR API would be kept private for the time being. Making it an officially supported API this early would bring a lot of pain in the future. This should still be documented, but the priority has dropped because of this.

**Comment by trevnorris** [comment]
Now that `socket-api` has been merged into `socket`, we will consider the IPC XHR API as internal. Hence no need for public documentation.
