### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by lacymorrow** [socketsupply/socket#877]
I didn't see your docs on github, so posting these here:

- "destkop": `Build mobile and destkop apps for any OS using HTML, CSS, and JavaScript.`

"resourcess": `It may be tempting to add a script tag that links to some online resourcess.`

- Protocol Design: `In the peper "Epidemic Broadcast Trees"`

**Comment by chicoxyzzy** [comment]
Thank you! Fixed
