### ISSUE TITLE
Publish '@socketsupply/socket' on NPM (and GH)

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#90]
There are two options for releasing on npm:

1. Include all the static libraries for all supported platforms in the npm module.
2. Post-install script to download the artifacts directly from someplace like S3.
3. Publish npm modules for each supported architecture and use a post-install script to `npm i` the module for the specific architecture.

Another consideration is ensuring developers have a comprehensive list of what they need. It's very possible that they npm install ssc just to have building an application fail since they don't have everything necessary.

**Comment by jwerle** [comment]
I did this for the `tusd-static` module a while ago which was just:

```js
const { platform } = process

try {
  module.exports = require(`tusd-static-${platform}`)
} catch (err) {
  const message = 'Unable to resolve a static `tusd(1)` binary for platform: ' + platform
  throw new Error(message)
}
```

where `tusd-static-{darwin,linux,win32}` were the variants

**Comment by trevnorris** [comment]
If we plan on supporting ARM in the future, even though we don't support it now, might want to make it `${platform}-${architecture}` to future-proof it.
