### ISSUE TITLE
Focus application window on Mac when applicationurl event is received

### ISSUE THREAD

**Issue by mjamesderocher** [socketsupply/socket#920]
If the app is minimized, when an app URL is called from the browser, an `applicationurl` event will fire, but the application stays minimized. It would be nice to be able to bring the application into focus.

I am not sure if this should be the default or something set with a setting.

**Comment by heapwolf** [comment]
you need the #921 to land so you can call `w.restore()`

**Comment by heapwolf** [comment]
landed. if you're on master, you can try it out.

**Comment by mjamesderocher** [comment]
It works for me! Thanks!
