### ISSUE TITLE
writefile not working correctly on Linux

### ISSUE THREAD

**Issue by WolfBearGames** [socketsupply/socket#932]
### What OS are you using (`uname -a`, or Windows version)?

Linux nobara-mini 6.7.0-204.fsync.fc39.x86_64 https://github.com/socketsupply/socket/pull/1 SMP PREEMPT_DYNAMIC TKG Wed Jan 17 09:24:55 UTC 2024 x86_64 GNU/Linux

### What version Socket Runtime are you using?

0.5.4

### What did you expect to see and what you saw instead?
```
await fs.writeFile(filepath, "Some String");
console.log("text saved to " + filepath);
```
Assuming "filepath" is a valid path to a .txt. file I would expect the content of the file is set to "Some String" and the log shows "text saved to ..."

Instead, the file is only partially overwritten from the beginning of the file (ist starts with "Some String" and then the rest of the previous content of the file follows. Additionally, the "console.log("text saved to " + filepath); line is never executed. The execution seems to be stuck.

On Windows the method works as expected (the complete file is overwritten with "Some String" and the console.log instruction is executed).

See an test app for reference:
[fs test app](https://github.com/WolfBearGames/socket-filesystem-test)

**Comment by jwerle** [comment]
this is fixed  now
