### ISSUE TITLE
Code Assessment/Cleanup

### ISSUE THREAD

**Issue by trevnorris** [socketsupply/socket#94]
The current state of the code is functional, but slowing down development on adding new features.  We'll need some dedicated time to do some cleanup and code restructuring. The primary goals are to:

1. Prevent issues like 78e2e2e7 from coming up that are easy to miss but difficult to find.
2. Make it easier for community contributors to help out.
3. Generalize how things are done.

This issue will track and discuss specifics.

**Comment by trevnorris** [comment]
Couple of things I'd like to address:

- The current state of nested lambdas in the Windows code makes it very difficult to reason about the application's state (it's unfortunate because the way our code is written follows the official WebView2 documentation, but that example code is not scaling well).
- Generalize how threads are created. This is a follow-up to 03f98a94 in that we don't launch threads frequently enough to require platform-specific thread spawning. Switching all platforms to use `std::thread()` should not have a noticeable performance difference.
- I'd like to embrace libuv more in our code. Now that libuv is a dependency, it makes sense that we replace our custom code with libuv API calls.

**Comment by mribbons** [comment]
- Refactor ``src/cli/cli.cc``:
In particular different platform build options, try to maintain overlap between target platforms where possible (ios, macos, linux)
It would be better to split out to separate files as it is quite tedious scrolling/searching up and down to make changes on platform
- Migrate inline functions to standard functions, these make it hard to link multiple .o files

**Comment by trevnorris** [comment]
As for the `cli.cc`, I want to take examples from how things are implemented in the official WebView2Samples repository (https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample) and redo the code. There's also utility code in there that could help us out.
