### ISSUE TITLE
No prebuilt binaries for desktop platforms

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [socketsupply/socket#980]
### What OS are you using (`uname -a`, or Windows version)?

Windows, Linux.

### What version Socket Runtime are you using?

0.5.4 (f90ba121)

### What programming language are you using (C/C++/Go/Rust)?

irrelevant

### What did you expect to see and what you saw instead?

Can I cross-build my apps on any machine without downloading additional dependencies, or relying on CI?

There must be a set of prebuilt binaries and build tools that download them and tweak metadata.

For implementation of cross-building for Windows:
Cross-platform signing, setting icons and patching Windows executables' metadata is easily done with `resedit` npm package. (Not the electron's `rcedit`, it requires Wine on non-windows machines.)

**Comment by heapwolf** [comment]
We ship prebuilt binaries just like other projects, you can install them with npm.

**Comment by CosmoMyzrailGorynych** [comment]
@heapwolf and how would one use them to make an app?
