### ISSUE TITLE
Discussion: Use POST mathod in Socket Runtime IPC

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#99]
### Synopsis

Theoretically, we can simplify our code by using `POST` method (and possibly RPC?) instead of (or additionally to) `GET` encoding/decoding URI. This way request body could be of any MIME type like `application/json`, `text/plain`, etc. This might be easier, faster and less error prone then using `GET` and URI parameters. Also, this can help with automatic generation of `.d.ts` for the Socket API client code or custom JS interfaces for the Socket Runtime.

### Example

Lets take the `window.setTitle` IPC message for example. Currently the Socket IPC is a `GET` request which looks like this:
```
ipc://window.setTitle?index=1&window=0&value=Hello%20World!
```
_Note: `Hello%20World!` is an encoded `"Hello World!"` string_

Here we have to write the code in `main.cc` by hands, which could be error-prone, especially if there is more parameters with different types and there are multiple parameters which should use `decodeURIComponent`

Alternative solution is a `POST` message with a body with a certain `content-type`:
```
Request: ipc://window.setTitle
Method: POST
Content-Type: application/json
```
Body:
```json
{
  "index": 1,
  "window": 0,
  "value": "Hello World!"
}
```
This is much easier to parse, but has a **disadvantage**: we need to have a JSON parser in the Socket Runtime.
This is an open question on how we can parse body, but one alternative is using `INI` parser we already use for the config. In that case request will look like this:
```
Request: ipc://window.setTitle
Method: POST
Content-Type: text/plain
```
Body:
```ini
index = 1
window = 0
value = "Hello World!"
```

### Typing
We can define a schema to automatically generate TypeScript definitions and possibly C++ code as well. For example we have such `schema.json` file (could be `INI`, `JSON Schema`, etc., I use custom schema in this example):
```json
{
  "window.setTitle": {
    "request": {
      "description": "Sets the window title"
      "properties": {
        "window" : {
          "description": "The window index"
          "optional": true,
          "default": 0,
          "type": "number"
        },
        "value": {
          "description": "The title to be set"
          "optional": false,
          "type": "string"
        }
      }
    }
  }
}
```
Same way the response could be specified here. This schema can help to generate types for the Socket API, which will include all the methods to use in the `window__ipc.postMessage`:
```ts
type Method =
  | 'window.getStatus'
  | 'window.getTitle'
  ...
```
and the inferred parameters for all the `Method` types via TypeScript's `infer`, so all of `window.__ipc.postMessage`, `socket.ipc.postMessage` (or `socket.ipc.send`, etc), `socket.runtime.setTitle` and their results are statically typed, have autocomplition and documentation.
This schema could generate the parts of `main.cc` and/or `bridge.cc` as well (before the push, w/ the header that this file is autogenerated)

### Open questions (besides those I've mentioned earlier)

- How useful would it be to allow binary MIME types like `application/octet-stream`, `image/gif`, `audio/mpeg`, `video/mpeg`, etc.?
- Can we use custom `content-type` to add support for https://github.com/socketsupply/ltp in future?

**Comment by jwerle** [comment]
Unfortunately I forgot to mention, Android and Linux do not support POST bodies in the intercepted requests

**Comment by chicoxyzzy** [comment]
Closing as won't fix
